version: 1
validation: sovereign
accounts: 
- name: pioneer1
  coins: ["100000000qdn"]
  mnemonic: "nest gown ability blouse ski tortoise wall female across know accuse guard shy drive grunt assault cricket solar pave arrange actress ring more country"
- name: sec-create-wallet-sponsor
  coins: ["10000000000qdn"]
  mnemonic: "guilt decline utility scale crash envelope snap table dress coach tray use detect success lemon fatigue surround project warfare victory mean midnight address before"
- name: treasury
  coins: ["100000000000qdn"]
- name: r-dsvs-as-app
  coins: ["10000000qdn"]
  mnemonic: "hope skate cattle float amount agent north belt remember wealth unfair tongue amazing sphere monkey guitar weekend kiss control peanut silent source tape rookie"
- name: r-ekyc-app
  coins: ["0qdn"]
  mnemonic: "blood dish hybrid toddler upgrade squirrel gate hazard raven wrong prevent lake battle acquire crack agree slam please autumn damage best skin gym call"
- name: coingecko-oracle
  coins: ["10000000qdn"]
  mnemonic: "area symptom room bomb atom relief give pole relief truly elbow unknown undo wild clutch ozone liar small occur off enjoy shop busy meadow"
- name: band-protocol-oracle
  coins: ["10000000qdn"]
  mnemonic: "verb select bread spirit beyond snow slender lumber ramp rule tribe soldier help area remove guard cage knife witness era mule afford wage like"
- name: coopnet-kyc-provider
  coins: ["10000000qdn"]
  mnemonic: "clarify whip jungle dune joke entry federal liquid pen journey reject flush evolve disorder slim upon stomach airport affair member occur code twice isolate"
- name: maya-kyc-provider
  coins: ["10000000qdn"]
  mnemonic: "penalty caution equip sound they soccer edge debris paddle add purity swap minute defense mass nature hood long diagram auction fat wish story minute"
- name: gcash-kyc-provider
  coins: ["10000000qdn"]
  mnemonic: "crunch theory census zoo olympic holiday they early chunk before humor word smile wisdom casual album nation perfect rotate toward have dress wear also"
- name: unionbank-kyc-provider
  coins: ["10000000qdn"]
  mnemonic: "among umbrella kingdom vote demise fetch eternal era lab thumb artefact tourist mail cactus album nation tuna fresh rule caution patch guilt body bean"
- name: testfinancesrvprv
  coins: ["10000000qdn"]
  mnemonic: "ill seed tent goose two trophy harsh noise winter conduct educate lady man spice sport charge primary fever acoustic famous message myth unlock dust"
- name: secidentitysrvprv
  coins: ["10000000000qdn"]
  mnemonic: "canoe oppose eternal occur film common dirt tomorrow lottery fun mask quote result account nasty tuna seat miracle have idle trophy frog catalog kiss"
- name: secdsvssrvprv
  coins: ["10000000000qdn"]
  mnemonic: "angry addict suit reform ostrich ride icon cushion park yellow wisdom mobile column sweet use anchor since tragic series ladder asthma dose prosper voice"

client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: pioneer1
  bonded: 10000qdn
  app:
    minimum-gas-prices: "0aqdn"
  config:
    log_level: "info"
    moniker: "pioneer1"
    consensus:
      timeout_propose: "3s"
    p2p:
      addr_book_strict: false
  client:
    chain-id: "qadena_1000-1"
build:
  main: cmd/qadenad

genesis:
  chain_id: "qadena_1000-1"
  app_state:
    staking:
      params:
        bond_denom: "aqdn"
    "bank": {
      "denom_metadata": [
        {
          "description": "",
          "denom_units": [
            {
              "denom": "aqdn",
              "exponent": 0,
              "aliases": []
            },
            {
              "denom": "qdn",
              "exponent": 18,
              "aliases": []
            }
          ],
          "base": "aqdn",
          "display": "qdn",
          "name": "Qadena Token",
          "symbol": "qdn"
        }
      ]
    }
    mint:
      params:
        mint_denom: "aqdn"
    gov:
      params:
        expedited_min_deposit:
          - denom: "aqdn"
            amount: "10000000000000000000"
        expedited_voting_period: "30s"
        min_deposit:
          - denom: "aqdn"
            amount: "1000000000000000000"
        voting_period: "300s"
