version: 1
validation: sovereign
accounts: 
- name: pioneer1
  coins: ["1000000qdn"]
  mnemonic: "nest gown ability blouse ski tortoise wall female across know accuse guard shy drive grunt assault cricket solar pave arrange actress ring more country"
- name: create-wallet-sponsor
  coins: ["100000qdn"]
  mnemonic: "guilt decline utility scale crash envelope snap table dress coach tray use detect success lemon fatigue surround project warfare victory mean midnight address before"
- name: treasury
  coins: ["2000000000qdn"] # 2 billion 
- name: ekycphidentitysrvprv
  coins: ["1000000qdn"]
  mnemonic: "blood dish hybrid toddler upgrade squirrel gate hazard raven wrong prevent lake battle acquire crack agree slam please autumn damage best skin gym call"
- name: coingecko-oracle
  coins: ["100000qdn"]
  mnemonic: "area symptom room bomb atom relief give pole relief truly elbow unknown undo wild clutch ozone liar small occur off enjoy shop busy meadow"
- name: band-protocol-oracle
  coins: ["100000qdn"]
  mnemonic: "verb select bread spirit beyond snow slender lumber ramp rule tribe soldier help area remove guard cage knife witness era mule afford wage like"
- name: coopnetidentitysrvprv
  coins: ["1000000qdn"]
  mnemonic: "clarify whip jungle dune joke entry federal liquid pen journey reject flush evolve disorder slim upon stomach airport affair member occur code twice isolate"
- name: mayaidentitysrvprv
  coins: ["1000000qdn"]
  mnemonic: "penalty caution equip sound they soccer edge debris paddle add purity swap minute defense mass nature hood long diagram auction fat wish story minute"
- name: coinsphidentitysrvprv
  coins: ["1000000qdn"]
  mnemonic: "crunch theory census zoo olympic holiday they early chunk before humor word smile wisdom casual album nation perfect rotate toward have dress wear also"
- name: unionbankidentitysrvprv
  coins: ["1000000qdn"]
  mnemonic: "among umbrella kingdom vote demise fetch eternal era lab thumb artefact tourist mail cactus album nation tuna fresh rule caution patch guilt body bean"
- name: testfinancesrvprv
  coins: ["1000000qdn"]
  mnemonic: "ill seed tent goose two trophy harsh noise winter conduct educate lady man spice sport charge primary fever acoustic famous message myth unlock dust"
- name: testidentitysrvprv
  coins: ["1000000qdn"]
  mnemonic: "lemon onion exit success feature wait admit permit nation behind vintage summer oven weird blue flash motor maple fiber domain cement inmate slogan avoid"
- name: testdsvssrvprv
  coins: ["1000000qdn"]
  mnemonic: "twenty shoulder tomato hawk toilet pave famous critic undo beef country object perfect staff net dilemma fade insane enemy oven barrel organ cherry problem"

client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: pioneer1
  bonded: 100000qdn
  app:
    minimum-gas-prices: "500000000aqdn"
    pruning: "custom"
    pruning-keep-recent: "2"
    pruning-interval: "5"
  config:
    log_level: "info"
    moniker: "pioneer1"
    consensus:
      timeout_propose: "3s"
    p2p:
      addr_book_strict: false
  client:
    chain-id: "qadena_1000-1"
build:
  main: cmd/qadenad

genesis:
  chain_id: "qadena_1000-1"
  app_state:
    staking:
      params:
        bond_denom: "aqdn"
    "bank": {
      "denom_metadata": [
        {
          "description": "",
          "denom_units": [
            {
              "denom": "aqdn",
              "exponent": 0,
              "aliases": []
            },
            {
              "denom": "qdn",
              "exponent": 18,
              "aliases": []
            }
          ],
          "base": "aqdn",
          "display": "qdn",
          "name": "Qadena Token",
          "symbol": "qdn"
        }
      ]
    }
    mint:
      params:
        mint_denom: "aqdn"
    gov:
      params:
        expedited_min_deposit:
          - denom: "aqdn"
            amount: "10000000000000000000"
        expedited_voting_period: "30s"
        min_deposit:
          - denom: "aqdn"
            amount: "1000000000000000000"
        voting_period: "300s"
    qadena:
      params:
        create_wallet_incentive:
          amount: "0"
          denom: "qdn"
        create_wallet_transparent_incentive:
          amount: "500"
          denom: "qdn"
        create_ephemeral_wallet_incentive:
          amount: "0"
          denom: "qdn"
        create_ephemeral_wallet_transparent_incentive:
          amount: "50"
          denom: "qdn"
        create_credential_fee: "30php"
        create_bulk_credentials_fee: "10php"
        ekyc_submit_new_app_royalty_percentage: "40"
        ekyc_submit_reuse_app_royalty_percentage: "20"
        ekyc_submit_reuse_provider_royalty_percentage: "20"
        ekyc_identity_owner_royalty_percentage: "30"
      enclaveIdentityList:
        - uniqueID: test-unique-id
          signerID: test-signer-id
          productID: test-product-id
          status: active
      publicKeyList:
        - pubKID: qadena1yxwh2nsxezlgwdgl5ve6gkxfjnf2w2yjavza8g
          pubK: AkXVN5vo4gHbEaQ81oEhMipW1+HbWt00nh7EoLl1PTsH
          pubKType: transaction
        - pubKID: qadena1yxwh2nsxezlgwdgl5ve6gkxfjnf2w2yjavza8g
          pubK: AkXVN5vo4gHbEaQ81oEhMipW1+HbWt00nh7EoLl1PTsH
          pubKType: credential
        - pubKID: testidentitysrvprvPubKID
          pubK: testidentitysrvprvPubK_pubk
          pubKType: transaction
        - pubKID: testidentitysrvprvPubKID
          pubK: testidentitysrvprvPubK_pubk
          pubKType: credential
        - pubKID: testdsvssrvprvPubKID
          pubK: testdsvssrvprvPubK_pubk
          pubKType: transaction
        - pubKID: testdsvssrvprvPubKID
          pubK: testdsvssrvprvPubK_pubk
          pubKType: credential
        - pubKID: testfinancesrvprvPubKID
          pubK: testfinancesrvprvPubK_pubk
          pubKType: transaction
        - pubKID: testfinancesrvprvPubKID
          pubK: testfinancesrvprvPubK_pubk
          pubKType: credential
        - pubKID: ekycphidentitysrvprvPubKID
          pubK: ekycphidentitysrvprvPubK_pubk
          pubKType: transaction
        - pubKID: ekycphidentitysrvprvPubKID
          pubK: ekycphidentitysrvprvPubK_pubk
          pubKType: credential
        - pubKID: mayaidentitysrvprvPubKID
          pubK: mayaidentitysrvprvPubK_pubk
          pubKType: transaction
        - pubKID: mayaidentitysrvprvPubKID
          pubK: mayaidentitysrvprvPubK_pubk
          pubKType: credential
        - pubKID: coopnetidentitysrvprvPubKID
          pubK: coopnetidentitysrvprvPubK_pubk
          pubKType: transaction
        - pubKID: coopnetidentitysrvprvPubKID
          pubK: coopnetidentitysrvprvPubK_pubk
          pubKType: credential
        - pubKID: coinsphidentitysrvprvPubKID
          pubK: coinsphidentitysrvprvPubK_pubk
          pubKType: transaction
        - pubKID: coinsphidentitysrvprvPubKID
          pubK: coinsphidentitysrvprvPubK_pubk
          pubKType: credential
        - pubKID: unionbankidentitysrvprvPubKID
          pubK: unionbankidentitysrvprvPubK_pubk
          pubKType: transaction
        - pubKID: unionbankidentitysrvprvPubKID
          pubK: unionbankidentitysrvprvPubK_pubk
          pubKType: credential
      intervalPublicKeyIDList:
        - pubKID: qadena1yxwh2nsxezlgwdgl5ve6gkxfjnf2w2yjavza8g
          nodeType: pioneer
          nodeID: pioneer1
        - pubKID: treasuryPubKID
          nodeType: treasury
          nodeID: treasury
        - pubKID: testidentitysrvprvPubKID
          nodeType: srv-prv
          nodeID: testidentitysrvprv
          serviceProviderType: identity
        - pubKID: testdsvssrvprvPubKID
          nodeType: srv-prv
          nodeID: testdsvssrvprv
          serviceProviderType: dsvs
        - pubKID: testfinancesrvprvPubKID
          nodeType: srv-prv
          nodeID: testfinancesrvprv
          serviceProviderType: finance
        - pubKID: ekycphidentitysrvprvPubKID
          nodeType: srv-prv
          nodeID: ekycphidentitysrvprv
          serviceProviderType: identity
        - pubKID: mayaidentitysrvprvPubKID
          nodeType: srv-prv
          nodeID: mayaidentitysrvprv
          serviceProviderType: identity
        - pubKID: coinsphidentitysrvprvPubKID
          nodeType: srv-prv
          nodeID: coinsphidentitysrvprv
          serviceProviderType: identity
        - pubKID: coopnetidentitysrvprvPubKID
          nodeType: srv-prv
          nodeID: coopnetidentitysrvprv
          serviceProviderType: identity
        - pubKID: unionbankidentitysrvprvPubKID
          nodeType: srv-prv
          nodeID: unionbankidentitysrvprv
          serviceProviderType: identity
    pricefeed:
      params:
        markets:
          - active: true
            baseAsset: "qdn"
            marketId: "cn:qdn:usd"
            quoteAsset: "usd"
            oracles:
              - "qadena138sf5wpu7lvxj3f65trha9ls7ktfwdd4yt76ng"
              - "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          - active: true
            baseAsset: "qdn"
            marketId: "cn:qdn:php"
            quoteAsset: "php"
            oracles:
              - "qadena138sf5wpu7lvxj3f65trha9ls7ktfwdd4yt76ng"
              - "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          - active: true
            baseAsset: "php"
            marketId: "fn:php:usd"
            quoteAsset: "usd"
            oracles:
              - "qadena138sf5wpu7lvxj3f65trha9ls7ktfwdd4yt76ng"
              - "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          - active: true
            baseAsset: "aud"
            marketId: "fn:aud:usd"
            quoteAsset: "usd"
            oracles:
              - "qadena138sf5wpu7lvxj3f65trha9ls7ktfwdd4yt76ng"
              - "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          - active: true
            baseAsset: "btc"
            marketId: "cn:btc:usd"
            quoteAsset: "usd"
            oracles:
              - "qadena138sf5wpu7lvxj3f65trha9ls7ktfwdd4yt76ng"
              - "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          - active: true
            baseAsset: "eth"
            marketId: "cn:eth:usd"
            quoteAsset: "usd"
            oracles:
              - "qadena138sf5wpu7lvxj3f65trha9ls7ktfwdd4yt76ng"
              - "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
      postedPriceList:
        - expiry: "2030-01-01T00:00:00Z"
          marketId: "cn:qdn:usd"
          oracleAddress: "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          price: "0.01"
        - expiry: "2030-01-01T00:00:00Z"
          marketId: "cn:qdn:php"
          oracleAddress: "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          price: "0.5713"
        - expiry: "2030-01-01T00:00:00Z"
          marketId: "fn:php:usd"
          oracleAddress: "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          price: "0.0174"
        - expiry: "2030-01-01T00:00:00Z"
          marketId: "fn:aud:usd"
          oracleAddress: "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          price: "0.676955"
        - expiry: "2030-01-01T00:00:00Z"
          marketId: "cn:btc:usd"
          oracleAddress: "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          price: "17217.06"
        - expiry: "2030-01-01T00:00:00Z"
          marketId: "cn:eth:usd"
          oracleAddress: "qadena1nzzpvqjj0j56rgtwqlk6r0gyj43j6a7hft87tg"
          price: "1282.63"
