// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qadena/dsvs/b_v_shared_secret.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BVSharedSecret struct {
	S1 *BECPoint `protobuf:"bytes,1,opt,name=S1,proto3" json:"S1,omitempty"`
	S2 *BECPoint `protobuf:"bytes,2,opt,name=S2,proto3" json:"S2,omitempty"`
}

func (m *BVSharedSecret) Reset()         { *m = BVSharedSecret{} }
func (m *BVSharedSecret) String() string { return proto.CompactTextString(m) }
func (*BVSharedSecret) ProtoMessage()    {}
func (*BVSharedSecret) Descriptor() ([]byte, []int) {
	return fileDescriptor_a195e9e143be6bd1, []int{0}
}
func (m *BVSharedSecret) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BVSharedSecret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BVSharedSecret.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BVSharedSecret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BVSharedSecret.Merge(m, src)
}
func (m *BVSharedSecret) XXX_Size() int {
	return m.Size()
}
func (m *BVSharedSecret) XXX_DiscardUnknown() {
	xxx_messageInfo_BVSharedSecret.DiscardUnknown(m)
}

var xxx_messageInfo_BVSharedSecret proto.InternalMessageInfo

func (m *BVSharedSecret) GetS1() *BECPoint {
	if m != nil {
		return m.S1
	}
	return nil
}

func (m *BVSharedSecret) GetS2() *BECPoint {
	if m != nil {
		return m.S2
	}
	return nil
}

func init() {
	proto.RegisterType((*BVSharedSecret)(nil), "qadena.dsvs.BVSharedSecret")
}

func init() {
	proto.RegisterFile("qadena/dsvs/b_v_shared_secret.proto", fileDescriptor_a195e9e143be6bd1)
}

var fileDescriptor_a195e9e143be6bd1 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x4c, 0x4c, 0x49,
	0xcd, 0x4b, 0xd4, 0x4f, 0x29, 0x2e, 0x2b, 0xd6, 0x4f, 0x8a, 0x2f, 0x8b, 0x2f, 0xce, 0x48, 0x2c,
	0x4a, 0x4d, 0x89, 0x2f, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x86, 0x28, 0xd2, 0x03, 0x29, 0x92, 0x92, 0x42, 0xd6, 0x91, 0x9a, 0x1c, 0x5f, 0x90, 0x9f,
	0x99, 0x07, 0x55, 0xa8, 0x14, 0xc7, 0xc5, 0xe7, 0x14, 0x16, 0x0c, 0x36, 0x21, 0x18, 0x6c, 0x80,
	0x90, 0x2a, 0x17, 0x53, 0xb0, 0xa1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xa8, 0x1e, 0x92,
	0x39, 0x7a, 0x4e, 0xae, 0xce, 0x01, 0x20, 0xad, 0x41, 0x4c, 0xc1, 0x86, 0x60, 0x65, 0x46, 0x12,
	0x4c, 0xf8, 0x95, 0x19, 0x39, 0x39, 0x9f, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83,
	0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43,
	0x94, 0x66, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0xb2, 0x71, 0x61,
	0x49, 0x6a, 0x72, 0x86, 0x3e, 0xc4, 0x98, 0xf8, 0x32, 0x63, 0xfd, 0x0a, 0x88, 0x6b, 0x4b, 0x2a,
	0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0x6e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x96, 0x8c,
	0x58, 0x63, 0xfb, 0x00, 0x00, 0x00,
}

func (m *BVSharedSecret) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BVSharedSecret) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BVSharedSecret) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.S2 != nil {
		{
			size, err := m.S2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBVSharedSecret(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.S1 != nil {
		{
			size, err := m.S1.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBVSharedSecret(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBVSharedSecret(dAtA []byte, offset int, v uint64) int {
	offset -= sovBVSharedSecret(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BVSharedSecret) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.S1 != nil {
		l = m.S1.Size()
		n += 1 + l + sovBVSharedSecret(uint64(l))
	}
	if m.S2 != nil {
		l = m.S2.Size()
		n += 1 + l + sovBVSharedSecret(uint64(l))
	}
	return n
}

func sovBVSharedSecret(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBVSharedSecret(x uint64) (n int) {
	return sovBVSharedSecret(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BVSharedSecret) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBVSharedSecret
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BVSharedSecret: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BVSharedSecret: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field S1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBVSharedSecret
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBVSharedSecret
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBVSharedSecret
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.S1 == nil {
				m.S1 = &BECPoint{}
			}
			if err := m.S1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field S2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBVSharedSecret
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBVSharedSecret
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBVSharedSecret
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.S2 == nil {
				m.S2 = &BECPoint{}
			}
			if err := m.S2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBVSharedSecret(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBVSharedSecret
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBVSharedSecret(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBVSharedSecret
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBVSharedSecret
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBVSharedSecret
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBVSharedSecret
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBVSharedSecret
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBVSharedSecret
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBVSharedSecret        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBVSharedSecret          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBVSharedSecret = fmt.Errorf("proto: unexpected end of group")
)
