// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qadena/qadena/credential.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Credential struct {
	CredentialID                 string           `protobuf:"bytes,1,opt,name=credentialID,proto3" json:"credentialID,omitempty"`
	CredentialType               string           `protobuf:"bytes,2,opt,name=credentialType,proto3" json:"credentialType,omitempty"`
	WalletID                     string           `protobuf:"bytes,3,opt,name=walletID,proto3" json:"walletID,omitempty"`
	CredentialPedersenCommit     *BPedersenCommit `protobuf:"bytes,4,opt,name=credentialPedersenCommit,proto3" json:"credentialPedersenCommit,omitempty"`
	EncCredentialHashVShare      []byte           `protobuf:"bytes,5,opt,name=encCredentialHashVShare,proto3" json:"encCredentialHashVShare,omitempty"`
	CredentialHashVShareBind     *VShareBindData  `protobuf:"bytes,6,opt,name=credentialHashVShareBind,proto3" json:"credentialHashVShareBind,omitempty"`
	EncCredentialInfoVShare      []byte           `protobuf:"bytes,7,opt,name=encCredentialInfoVShare,proto3" json:"encCredentialInfoVShare,omitempty"`
	CredentialInfoVShareBind     *VShareBindData  `protobuf:"bytes,8,opt,name=credentialInfoVShareBind,proto3" json:"credentialInfoVShareBind,omitempty"`
	FindCredentialPedersenCommit *BPedersenCommit `protobuf:"bytes,9,opt,name=findCredentialPedersenCommit,proto3" json:"findCredentialPedersenCommit,omitempty"`
	ProviderWalletID             string           `protobuf:"bytes,10,opt,name=providerWalletID,proto3" json:"providerWalletID,omitempty"`
	ReferenceCredentialID        string           `protobuf:"bytes,11,opt,name=referenceCredentialID,proto3" json:"referenceCredentialID,omitempty"`
	IdentityOwnerWalletID        string           `protobuf:"bytes,12,opt,name=identityOwnerWalletID,proto3" json:"identityOwnerWalletID,omitempty"`
	EkycAppWalletID              string           `protobuf:"bytes,13,opt,name=ekycAppWalletID,proto3" json:"ekycAppWalletID,omitempty"`
}

func (m *Credential) Reset()         { *m = Credential{} }
func (m *Credential) String() string { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()    {}
func (*Credential) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f95d2b506b702bc, []int{0}
}
func (m *Credential) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Credential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Credential.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Credential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credential.Merge(m, src)
}
func (m *Credential) XXX_Size() int {
	return m.Size()
}
func (m *Credential) XXX_DiscardUnknown() {
	xxx_messageInfo_Credential.DiscardUnknown(m)
}

var xxx_messageInfo_Credential proto.InternalMessageInfo

func (m *Credential) GetCredentialID() string {
	if m != nil {
		return m.CredentialID
	}
	return ""
}

func (m *Credential) GetCredentialType() string {
	if m != nil {
		return m.CredentialType
	}
	return ""
}

func (m *Credential) GetWalletID() string {
	if m != nil {
		return m.WalletID
	}
	return ""
}

func (m *Credential) GetCredentialPedersenCommit() *BPedersenCommit {
	if m != nil {
		return m.CredentialPedersenCommit
	}
	return nil
}

func (m *Credential) GetEncCredentialHashVShare() []byte {
	if m != nil {
		return m.EncCredentialHashVShare
	}
	return nil
}

func (m *Credential) GetCredentialHashVShareBind() *VShareBindData {
	if m != nil {
		return m.CredentialHashVShareBind
	}
	return nil
}

func (m *Credential) GetEncCredentialInfoVShare() []byte {
	if m != nil {
		return m.EncCredentialInfoVShare
	}
	return nil
}

func (m *Credential) GetCredentialInfoVShareBind() *VShareBindData {
	if m != nil {
		return m.CredentialInfoVShareBind
	}
	return nil
}

func (m *Credential) GetFindCredentialPedersenCommit() *BPedersenCommit {
	if m != nil {
		return m.FindCredentialPedersenCommit
	}
	return nil
}

func (m *Credential) GetProviderWalletID() string {
	if m != nil {
		return m.ProviderWalletID
	}
	return ""
}

func (m *Credential) GetReferenceCredentialID() string {
	if m != nil {
		return m.ReferenceCredentialID
	}
	return ""
}

func (m *Credential) GetIdentityOwnerWalletID() string {
	if m != nil {
		return m.IdentityOwnerWalletID
	}
	return ""
}

func (m *Credential) GetEkycAppWalletID() string {
	if m != nil {
		return m.EkycAppWalletID
	}
	return ""
}

// clone alert, this is also in nameservice/tx.proto!!!!
type MsgBindCredential struct {
	Creator             string           `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CredentialType      string           `protobuf:"bytes,2,opt,name=credentialType,proto3" json:"credentialType,omitempty"`
	CredentialInfo      string           `protobuf:"bytes,3,opt,name=credentialInfo,proto3" json:"credentialInfo,omitempty"`
	ProofPedersenCommit *BPedersenCommit `protobuf:"bytes,4,opt,name=proofPedersenCommit,proto3" json:"proofPedersenCommit,omitempty"`
}

func (m *MsgBindCredential) Reset()         { *m = MsgBindCredential{} }
func (m *MsgBindCredential) String() string { return proto.CompactTextString(m) }
func (*MsgBindCredential) ProtoMessage()    {}
func (*MsgBindCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f95d2b506b702bc, []int{1}
}
func (m *MsgBindCredential) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBindCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBindCredential.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBindCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBindCredential.Merge(m, src)
}
func (m *MsgBindCredential) XXX_Size() int {
	return m.Size()
}
func (m *MsgBindCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBindCredential.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBindCredential proto.InternalMessageInfo

func (m *MsgBindCredential) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgBindCredential) GetCredentialType() string {
	if m != nil {
		return m.CredentialType
	}
	return ""
}

func (m *MsgBindCredential) GetCredentialInfo() string {
	if m != nil {
		return m.CredentialInfo
	}
	return ""
}

func (m *MsgBindCredential) GetProofPedersenCommit() *BPedersenCommit {
	if m != nil {
		return m.ProofPedersenCommit
	}
	return nil
}

type MsgBindCredentialResponse struct {
}

func (m *MsgBindCredentialResponse) Reset()         { *m = MsgBindCredentialResponse{} }
func (m *MsgBindCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBindCredentialResponse) ProtoMessage()    {}
func (*MsgBindCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f95d2b506b702bc, []int{2}
}
func (m *MsgBindCredentialResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBindCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBindCredentialResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBindCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBindCredentialResponse.Merge(m, src)
}
func (m *MsgBindCredentialResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBindCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBindCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBindCredentialResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Credential)(nil), "qadena.qadena.Credential")
	proto.RegisterType((*MsgBindCredential)(nil), "qadena.qadena.MsgBindCredential")
	proto.RegisterType((*MsgBindCredentialResponse)(nil), "qadena.qadena.MsgBindCredentialResponse")
}

func init() { proto.RegisterFile("qadena/qadena/credential.proto", fileDescriptor_8f95d2b506b702bc) }

var fileDescriptor_8f95d2b506b702bc = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x8e, 0x12, 0x41,
	0x14, 0xa5, 0x7d, 0x30, 0x33, 0x77, 0x18, 0x1f, 0x65, 0x8c, 0x2d, 0x6a, 0x87, 0x60, 0x34, 0x44,
	0x13, 0x48, 0xc4, 0x85, 0x5b, 0x01, 0x13, 0x59, 0x18, 0x27, 0xad, 0xd1, 0x38, 0x9b, 0x4e, 0x75,
	0xf5, 0x65, 0xe8, 0x08, 0x55, 0x35, 0xd5, 0x25, 0x23, 0x7f, 0xe1, 0x27, 0xf8, 0x39, 0xee, 0x9c,
	0xa5, 0x4b, 0x03, 0x3f, 0x62, 0xa8, 0x6e, 0x68, 0x8a, 0x87, 0x41, 0x57, 0x95, 0x7b, 0xee, 0x39,
	0x70, 0x6e, 0xdf, 0x07, 0x78, 0x67, 0x34, 0x42, 0x4e, 0x1b, 0xd9, 0xc3, 0x14, 0x46, 0xc8, 0x75,
	0x4c, 0x07, 0x75, 0xa9, 0x84, 0x16, 0xe4, 0x28, 0x4d, 0xd4, 0xd3, 0xa7, 0xfc, 0xd0, 0xa6, 0x4b,
	0x8c, 0x50, 0x25, 0xc8, 0x03, 0x26, 0x86, 0xc3, 0x58, 0xa7, 0x9a, 0xf2, 0x23, 0x9b, 0x14, 0x06,
	0x3b, 0xd1, 0x46, 0x41, 0xd2, 0xa7, 0x0a, 0x83, 0x30, 0xe6, 0x51, 0x10, 0x51, 0x4d, 0x53, 0x5a,
	0xf5, 0x7b, 0x11, 0xa0, 0xbd, 0xb0, 0x45, 0xaa, 0x50, 0xca, 0x4d, 0x76, 0x3b, 0xae, 0x53, 0x71,
	0x6a, 0x07, 0xbe, 0x85, 0x91, 0xc7, 0x70, 0x2d, 0x8f, 0xdf, 0x8f, 0x25, 0xba, 0x97, 0x0c, 0x6b,
	0x05, 0x25, 0x65, 0xd8, 0x3f, 0xa7, 0x83, 0x01, 0xea, 0x6e, 0xc7, 0xbd, 0x6c, 0x18, 0x8b, 0x98,
	0x9c, 0x80, 0x9b, 0xb3, 0x8f, 0xb3, 0x02, 0xda, 0xc6, 0xbf, 0x7b, 0xa5, 0xe2, 0xd4, 0x0e, 0x9f,
	0x79, 0x75, 0xeb, 0xdb, 0xd4, 0x5b, 0x36, 0xcb, 0xdf, 0xaa, 0x27, 0x2f, 0xe0, 0x0e, 0x72, 0x96,
	0x17, 0xf5, 0x9a, 0x26, 0xfd, 0x0f, 0xef, 0x66, 0xd5, 0xbb, 0x57, 0x2b, 0x4e, 0xad, 0xe4, 0x6f,
	0x4b, 0x93, 0x4f, 0xcb, 0xae, 0x72, 0xbc, 0x15, 0xf3, 0xc8, 0x2d, 0x1a, 0x57, 0x0f, 0x56, 0x5c,
	0xe5, 0x84, 0x0e, 0xd5, 0xd4, 0xdf, 0x2a, 0x5f, 0x33, 0xd5, 0xe5, 0x3d, 0x91, 0x99, 0xda, 0xdb,
	0x60, 0x2a, 0x4f, 0xdb, 0xa6, 0x72, 0xdc, 0x98, 0xda, 0xff, 0x47, 0x53, 0xb6, 0x9c, 0x84, 0x70,
	0xbf, 0x17, 0xf3, 0xa8, 0xbd, 0xad, 0x13, 0x07, 0x3b, 0x75, 0xe2, 0xaf, 0xbf, 0x41, 0x9e, 0xc0,
	0x0d, 0xa9, 0xc4, 0x28, 0x8e, 0x50, 0x7d, 0x9c, 0x4f, 0x03, 0x98, 0x69, 0x58, 0xc3, 0xc9, 0x73,
	0xb8, 0xad, 0xb0, 0x87, 0x0a, 0x39, 0xc3, 0xf6, 0xf2, 0x18, 0x1e, 0x1a, 0xc1, 0xe6, 0xe4, 0x4c,
	0x15, 0x9b, 0x48, 0x8f, 0xdf, 0x9e, 0xf3, 0xa5, 0xbf, 0x29, 0xa5, 0xaa, 0x8d, 0x49, 0x52, 0x83,
	0xeb, 0xf8, 0x79, 0xcc, 0x5e, 0x4a, 0xb9, 0xe0, 0x1f, 0x19, 0xfe, 0x2a, 0x5c, 0xfd, 0xe9, 0xc0,
	0xcd, 0x37, 0xc9, 0x69, 0xcb, 0xaa, 0x92, 0xb8, 0xb0, 0xc7, 0x14, 0x52, 0x2d, 0x54, 0xb6, 0x24,
	0xf3, 0x70, 0xe7, 0xfd, 0xb0, 0x78, 0xb3, 0xce, 0x64, 0x5b, 0xb2, 0x82, 0x92, 0x63, 0xb8, 0x25,
	0x95, 0x10, 0xbd, 0xff, 0x5a, 0x93, 0x4d, 0xd2, 0xea, 0x3d, 0xb8, 0xbb, 0x56, 0x90, 0x8f, 0x89,
	0x14, 0x3c, 0xc1, 0xd6, 0xab, 0x1f, 0x13, 0xcf, 0xb9, 0x98, 0x78, 0xce, 0xef, 0x89, 0xe7, 0x7c,
	0x9b, 0x7a, 0x85, 0x8b, 0xa9, 0x57, 0xf8, 0x35, 0xf5, 0x0a, 0x27, 0x4f, 0x4f, 0x63, 0xdd, 0xff,
	0x12, 0xd6, 0x99, 0x18, 0x36, 0x58, 0xf3, 0x4c, 0x23, 0xeb, 0x67, 0xe7, 0x25, 0x18, 0x35, 0x1b,
	0x5f, 0xe7, 0xa7, 0x46, 0x8f, 0x25, 0x26, 0x61, 0xd1, 0xdc, 0x97, 0xe6, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x73, 0x76, 0xea, 0xc4, 0x03, 0x05, 0x00, 0x00,
}

func (m *Credential) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Credential) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Credential) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EkycAppWalletID) > 0 {
		i -= len(m.EkycAppWalletID)
		copy(dAtA[i:], m.EkycAppWalletID)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.EkycAppWalletID)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.IdentityOwnerWalletID) > 0 {
		i -= len(m.IdentityOwnerWalletID)
		copy(dAtA[i:], m.IdentityOwnerWalletID)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.IdentityOwnerWalletID)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.ReferenceCredentialID) > 0 {
		i -= len(m.ReferenceCredentialID)
		copy(dAtA[i:], m.ReferenceCredentialID)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.ReferenceCredentialID)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ProviderWalletID) > 0 {
		i -= len(m.ProviderWalletID)
		copy(dAtA[i:], m.ProviderWalletID)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.ProviderWalletID)))
		i--
		dAtA[i] = 0x52
	}
	if m.FindCredentialPedersenCommit != nil {
		{
			size, err := m.FindCredentialPedersenCommit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCredential(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.CredentialInfoVShareBind != nil {
		{
			size, err := m.CredentialInfoVShareBind.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCredential(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if len(m.EncCredentialInfoVShare) > 0 {
		i -= len(m.EncCredentialInfoVShare)
		copy(dAtA[i:], m.EncCredentialInfoVShare)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.EncCredentialInfoVShare)))
		i--
		dAtA[i] = 0x3a
	}
	if m.CredentialHashVShareBind != nil {
		{
			size, err := m.CredentialHashVShareBind.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCredential(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.EncCredentialHashVShare) > 0 {
		i -= len(m.EncCredentialHashVShare)
		copy(dAtA[i:], m.EncCredentialHashVShare)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.EncCredentialHashVShare)))
		i--
		dAtA[i] = 0x2a
	}
	if m.CredentialPedersenCommit != nil {
		{
			size, err := m.CredentialPedersenCommit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCredential(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.WalletID) > 0 {
		i -= len(m.WalletID)
		copy(dAtA[i:], m.WalletID)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.WalletID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CredentialType) > 0 {
		i -= len(m.CredentialType)
		copy(dAtA[i:], m.CredentialType)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.CredentialType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CredentialID) > 0 {
		i -= len(m.CredentialID)
		copy(dAtA[i:], m.CredentialID)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.CredentialID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBindCredential) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBindCredential) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBindCredential) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProofPedersenCommit != nil {
		{
			size, err := m.ProofPedersenCommit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCredential(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.CredentialInfo) > 0 {
		i -= len(m.CredentialInfo)
		copy(dAtA[i:], m.CredentialInfo)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.CredentialInfo)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CredentialType) > 0 {
		i -= len(m.CredentialType)
		copy(dAtA[i:], m.CredentialType)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.CredentialType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBindCredentialResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBindCredentialResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBindCredentialResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintCredential(dAtA []byte, offset int, v uint64) int {
	offset -= sovCredential(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Credential) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CredentialID)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.CredentialType)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.WalletID)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	if m.CredentialPedersenCommit != nil {
		l = m.CredentialPedersenCommit.Size()
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.EncCredentialHashVShare)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	if m.CredentialHashVShareBind != nil {
		l = m.CredentialHashVShareBind.Size()
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.EncCredentialInfoVShare)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	if m.CredentialInfoVShareBind != nil {
		l = m.CredentialInfoVShareBind.Size()
		n += 1 + l + sovCredential(uint64(l))
	}
	if m.FindCredentialPedersenCommit != nil {
		l = m.FindCredentialPedersenCommit.Size()
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.ProviderWalletID)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.ReferenceCredentialID)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.IdentityOwnerWalletID)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.EkycAppWalletID)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	return n
}

func (m *MsgBindCredential) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.CredentialType)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.CredentialInfo)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	if m.ProofPedersenCommit != nil {
		l = m.ProofPedersenCommit.Size()
		n += 1 + l + sovCredential(uint64(l))
	}
	return n
}

func (m *MsgBindCredentialResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovCredential(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCredential(x uint64) (n int) {
	return sovCredential(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Credential) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCredential
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Credential: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Credential: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialPedersenCommit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CredentialPedersenCommit == nil {
				m.CredentialPedersenCommit = &BPedersenCommit{}
			}
			if err := m.CredentialPedersenCommit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncCredentialHashVShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncCredentialHashVShare = append(m.EncCredentialHashVShare[:0], dAtA[iNdEx:postIndex]...)
			if m.EncCredentialHashVShare == nil {
				m.EncCredentialHashVShare = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialHashVShareBind", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CredentialHashVShareBind == nil {
				m.CredentialHashVShareBind = &VShareBindData{}
			}
			if err := m.CredentialHashVShareBind.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncCredentialInfoVShare", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncCredentialInfoVShare = append(m.EncCredentialInfoVShare[:0], dAtA[iNdEx:postIndex]...)
			if m.EncCredentialInfoVShare == nil {
				m.EncCredentialInfoVShare = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialInfoVShareBind", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CredentialInfoVShareBind == nil {
				m.CredentialInfoVShareBind = &VShareBindData{}
			}
			if err := m.CredentialInfoVShareBind.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FindCredentialPedersenCommit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FindCredentialPedersenCommit == nil {
				m.FindCredentialPedersenCommit = &BPedersenCommit{}
			}
			if err := m.FindCredentialPedersenCommit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderWalletID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderWalletID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferenceCredentialID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReferenceCredentialID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityOwnerWalletID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentityOwnerWalletID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EkycAppWalletID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EkycAppWalletID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCredential(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCredential
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBindCredential) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCredential
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBindCredential: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBindCredential: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialInfo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialInfo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofPedersenCommit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProofPedersenCommit == nil {
				m.ProofPedersenCommit = &BPedersenCommit{}
			}
			if err := m.ProofPedersenCommit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCredential(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCredential
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBindCredentialResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCredential
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBindCredentialResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBindCredentialResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipCredential(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCredential
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCredential(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCredential
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCredential
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCredential
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCredential
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCredential        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCredential          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCredential = fmt.Errorf("proto: unexpected end of group")
)
