// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qadena/qadena/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	CreateWalletIncentive                     types.Coin `protobuf:"bytes,1,opt,name=create_wallet_incentive,json=createWalletIncentive,proto3" json:"create_wallet_incentive" yaml:"create_wallet_incentive"`
	CreateEphemeralWalletIncentive            types.Coin `protobuf:"bytes,2,opt,name=create_ephemeral_wallet_incentive,json=createEphemeralWalletIncentive,proto3" json:"create_ephemeral_wallet_incentive" yaml:"create_ephemeral_wallet_incentive"`
	CreateWalletTransparentIncentive          types.Coin `protobuf:"bytes,3,opt,name=create_wallet_transparent_incentive,json=createWalletTransparentIncentive,proto3" json:"create_wallet_transparent_incentive" yaml:"create_wallet_transparent_incentive"`
	CreateEphemeralWalletTransparentIncentive types.Coin `protobuf:"bytes,4,opt,name=create_ephemeral_wallet_transparent_incentive,json=createEphemeralWalletTransparentIncentive,proto3" json:"create_ephemeral_wallet_transparent_incentive" yaml:"create_ephemeral_wallet_transparent_incentive"`
	CreateCredentialFee                       string     `protobuf:"bytes,5,opt,name=create_credential_fee,json=createCredentialFee,proto3" json:"create_credential_fee,omitempty"`
	EkycSubmitNewAppRoyaltyPercentage         string     `protobuf:"bytes,6,opt,name=ekyc_submit_new_app_royalty_percentage,json=ekycSubmitNewAppRoyaltyPercentage,proto3" json:"ekyc_submit_new_app_royalty_percentage,omitempty"`
	EkycSubmitReuseAppRoyaltyPercentage       string     `protobuf:"bytes,7,opt,name=ekyc_submit_reuse_app_royalty_percentage,json=ekycSubmitReuseAppRoyaltyPercentage,proto3" json:"ekyc_submit_reuse_app_royalty_percentage,omitempty"`
	EkycSubmitReuseProviderRoyaltyPercentage  string     `protobuf:"bytes,8,opt,name=ekyc_submit_reuse_provider_royalty_percentage,json=ekycSubmitReuseProviderRoyaltyPercentage,proto3" json:"ekyc_submit_reuse_provider_royalty_percentage,omitempty"`
	EkycIdentityOwnerRoyaltyPercentage        string     `protobuf:"bytes,9,opt,name=ekyc_identity_owner_royalty_percentage,json=ekycIdentityOwnerRoyaltyPercentage,proto3" json:"ekyc_identity_owner_royalty_percentage,omitempty"`
	CreateBulkCredentialsFee                  string     `protobuf:"bytes,10,opt,name=create_bulk_credentials_fee,json=createBulkCredentialsFee,proto3" json:"create_bulk_credentials_fee,omitempty"`
	// MsgUpdateCredential.  Every numeric here reads as zero on a chain that predates these
	// params, so the policy loader substitutes the compiled-in defaults in
	// x/qadena/common/credential_policy.go rather than rejecting every correction.  The
	// birthdate month/day-swap exception is deliberately NOT a param: it is part of what the
	// birthdate rule MEANS, not a quantity to tune.
	UpdateCredentialFee string `protobuf:"bytes,11,opt,name=update_credential_fee,json=updateCredentialFee,proto3" json:"update_credential_fee,omitempty"`
	// bumped whenever the policy engine's behaviour changes, so a divergence between enclave
	// builds is visible on chain instead of silent
	UpdateCredentialPolicyVersion uint32 `protobuf:"varint,12,opt,name=update_credential_policy_version,json=updateCredentialPolicyVersion,proto3" json:"update_credential_policy_version,omitempty"`
	// cap on entries in a credential's identity-hash alias list; the list length is the
	// hash-changing-update counter, so this is the lifetime update limit plus one
	UpdateCredentialMaxIdentityAliases      uint32 `protobuf:"varint,13,opt,name=update_credential_max_identity_aliases,json=updateCredentialMaxIdentityAliases,proto3" json:"update_credential_max_identity_aliases,omitempty"`
	UpdateCredentialMaxLifeEvents           uint32 `protobuf:"varint,14,opt,name=update_credential_max_life_events,json=updateCredentialMaxLifeEvents,proto3" json:"update_credential_max_life_events,omitempty"`
	UpdateNameMaxEditDistance               uint32 `protobuf:"varint,15,opt,name=update_name_max_edit_distance,json=updateNameMaxEditDistance,proto3" json:"update_name_max_edit_distance,omitempty"`
	UpdateNameMaxEditDistancePercent        uint32 `protobuf:"varint,16,opt,name=update_name_max_edit_distance_percent,json=updateNameMaxEditDistancePercent,proto3" json:"update_name_max_edit_distance_percent,omitempty"`
	UpdateBirthdateMaxYearDelta             uint32 `protobuf:"varint,17,opt,name=update_birthdate_max_year_delta,json=updateBirthdateMaxYearDelta,proto3" json:"update_birthdate_max_year_delta,omitempty"`
	UpdateCredentialMinBlocksBetweenUpdates int64  `protobuf:"varint,18,opt,name=update_credential_min_blocks_between_updates,json=updateCredentialMinBlocksBetweenUpdates,proto3" json:"update_credential_min_blocks_between_updates,omitempty"`
	// gates so a jurisdiction can disable a transition by param rather than by fork
	UpdateCredentialAllowLastNameLifeEvent bool `protobuf:"varint,19,opt,name=update_credential_allow_last_name_life_event,json=updateCredentialAllowLastNameLifeEvent,proto3" json:"update_credential_allow_last_name_life_event,omitempty"`
	UpdateCredentialAllowGenderChange      bool `protobuf:"varint,20,opt,name=update_credential_allow_gender_change,json=updateCredentialAllowGenderChange,proto3" json:"update_credential_allow_gender_change,omitempty"`
	// The AML scan in the enclave (ScanTransaction).  Two rules use these: a single transfer at or
	// above the threshold, and the rolling-window total from one source to one destination reaching
	// it.  Like the update-credential block above, an empty string or a zero reads as UNSET on a
	// chain that predates these params, so SuspiciousPolicyFromParams substitutes the compiled-in
	// defaults.  It must never interpret them literally: a zero threshold would flag every transfer
	// and a zero window would expire the history instantly, silently disabling the aggregate rule.
	SuspiciousTransactionThreshold string `protobuf:"bytes,21,opt,name=suspicious_transaction_threshold,json=suspiciousTransactionThreshold,proto3" json:"suspicious_transaction_threshold,omitempty"`
	// Length of the rolling window.  Measured against the BLOCK time supplied to the enclave, never
	// wall clock -- the scan runs on every validator and its verdict decides whether the transfer is
	// rejected, so a non-deterministic clock here would fork the chain.
	SuspiciousTransactionWindowSeconds int64 `protobuf:"varint,22,opt,name=suspicious_transaction_window_seconds,json=suspiciousTransactionWindowSeconds,proto3" json:"suspicious_transaction_window_seconds,omitempty"`
	// Per-jurisdiction thresholds, because the reporting limit is a legal number set locally and not
	// a converted one: PH files at PHP 500,000, the US at USD 10,000.  Anything not listed here falls
	// back to suspicious_transaction_threshold.
	SuspiciousTransactionThresholdOverrides []SuspiciousThresholdOverride `protobuf:"bytes,23,rep,name=suspicious_transaction_threshold_overrides,json=suspiciousTransactionThresholdOverrides,proto3" json:"suspicious_transaction_threshold_overrides"`
	// Whether a wallet with no claimed credential may send at all.  Named for what it PERMITS so
	// that proto3's zero value (false) is the ENFORCING state: an unset param must never silently
	// switch an AML control off, and every other spelling of this flag would do exactly that on a
	// chain whose params predate it.
	AllowTransferWithoutEkyc bool `protobuf:"varint,24,opt,name=allow_transfer_without_ekyc,json=allowTransferWithoutEkyc,proto3" json:"allow_transfer_without_ekyc,omitempty"`
	// What to do with a reportable transfer whose sender gave no --opt-in-reason.
	//
	// FALSE (default): file the report anyway, substituting "No reason provided", and let the
	// transfer through.  TRUE: refuse it and file nothing, which is what this chain did before the
	// flag existed.
	//
	// The old behaviour made every report self-selected: a sender unwilling to be named was blocked
	// rather than reported, so the regulator saw only volunteered transfers and never the refusals.
	// Defaulting to false means an un-upgraded chain starts producing MORE reports, never fewer,
	// which is why the proto3 zero is safe here even though it reads as "do not block".
	BlockTransferWithoutOptInReason bool `protobuf:"varint,26,opt,name=block_transfer_without_opt_in_reason,json=blockTransferWithoutOptInReason,proto3" json:"block_transfer_without_opt_in_reason,omitempty"`
	// How many identity-bearing fields (first/middle/last name, birthdate, gender) may change in a
	// single MsgUpdateCredential.
	//
	// ONE IS THE SAFE VALUE AND THE DEFAULT.  Two simultaneous changes are hard to distinguish from
	// substituting one person for another, which is why this was a compiled-in constant until it
	// became a param.  A zero here reads as UNSET and yields 1, so a chain whose params predate this
	// keeps exactly the behaviour it had.
	//
	// Raising it also weakens the surname life-event rule, which is only safe because the remaining
	// identity fields still pin the identity while the surname is replaced wholesale.  A chain that
	// allows a life event AND another edit in one update has given up that anchor.
	UpdateCredentialMaxChangedIdentityFields uint32 `protobuf:"varint,25,opt,name=update_credential_max_changed_identity_fields,json=updateCredentialMaxChangedIdentityFields,proto3" json:"update_credential_max_changed_identity_fields,omitempty"`
	// Whether an INSTITUTIONAL guardian must state, in MsgSignRecoverPrivateKey, the identity it
	// verified -- so the enclave can resolve that identity to a wallet itself and refuse to sign
	// anything else.
	//
	//   0 = off      do not look at the assertion at all (pre-upgrade behaviour)
	//   1 = audit    resolve and compare, LOG a mismatch, still accept
	//   2 = enforce  resolve and compare, log, and REJECT a mismatch
	//
	// Guardians matched as a raw bech32 address (family and friends) are exempt in every mode: the
	// hole this closes is specific to a SERVER resolving identity->wallet on its own side, which an
	// individual signing from their own app does not do, and CreateCredentialHash needs all five
	// identity fields byte-exact after canonicalization, so a human could not comply reliably.
	//
	// AN ENUM IN A uint32, NOT A bool, because "verify but do not reject yet" is the state this
	// whole change is built around.  The scheme rests on one unproven invariant -- that the hash a
	// guardian computes at signing time equals the one issuance produced -- and if that is wrong,
	// enforcing it fails every institutional signature closed.  Mode 1 proves it against real
	// traffic first.  Validate() rejects anything above 2.
	//
	// THE DIRECTION IS THE OPPOSITE OF allow_transfer_without_ekyc (24), deliberately.  That flag is
	// named so proto3's zero is the ENFORCING state, because an unset param must never silently
	// switch an AML control off.  That reasoning does not carry here: this control does not exist
	// before the upgrade, and no guardian has ever sent an assertion, so a zero that meant "enforce"
	// would break every institutional signature on an un-upgraded chain the moment it upgraded.
	// Zero therefore means "behave exactly as before", which is the same exception
	// block_transfer_without_opt_in_reason (26) documents for itself.
	SignRecoverKeyGuardianAssertionMode uint32 `protobuf:"varint,27,opt,name=sign_recover_key_guardian_assertion_mode,json=signRecoverKeyGuardianAssertionMode,proto3" json:"sign_recover_key_guardian_assertion_mode,omitempty"`
	// Whether a validator leaving the bonded set has its pioneer row's ExternalIPAddress cleared
	// (parked, and restored when it re-bonds).  The published address is a SECURITY PARAMETER: the
	// enclave's owner-candidate set for every NEW secret-share interval key is exactly the pioneer
	// rows with a non-empty address, and it also sizes the share threshold and the enclave-identity
	// vote quorum.  Without this, a validator that unbonds or is jailed counts as a share owner
	// forever.
	//
	// TURNING IT OFF STOPS NEW PARKING ONLY.  An address parked while it was on is still restored
	// when its validator re-bonds; otherwise switching this off with a validator mid-jail would
	// leave that pioneer bonded but permanently unaddressable, since the enclave never fills an
	// empty row and re-enabling the param cannot replay a re-bond that already happened.
	//
	// TRUE BY DEFAULT.  DefaultParams sets it, and both config/config.yml and
	// config/launch-config.yml state it, so every chain launched from here has it on; a chain must
	// opt OUT, not in.
	//
	// THE UNAVOIDABLE EXCEPTION IS STORED STATE THAT PREDATES THE FIELD.  Params bytes written before
	// field 28 existed carry no 28, so they unmarshal as proto3's false, and GetParams on an empty
	// store returns the zero value too.  Neither can be defaulted away, and neither should be: a new
	// binary replaying such a chain's history must reproduce the app hashes the old binary produced,
	// and hooks firing at a height where they originally did not would fork the state root.  (The
	// empty-store case also covers bootstrap ordering for free -- genesis validators bond during
	// staking's InitGenesis, before qadena's has run.)  Such a chain turns it on by governance
	// (MsgUpdateParams -- which replaces the WHOLE params object, see the NOTE below), which records
	// the change at a height that replay can follow.
	ReleaseAddressOnUnbond bool `protobuf:"varint,28,opt,name=release_address_on_unbond,json=releaseAddressOnUnbond,proto3" json:"release_address_on_unbond,omitempty"`
	// Governance's half of the enclave trust policy.  A BLOCK rather than a bare field so the knobs
	// that follow (attestation age, rollback freeze) are additive and do not each claim a Params
	// number of their own.
	//
	// EMPTY IS UNRESTRICTED, and it has to be.  Params bytes written before field 29 carry no 29, and
	// GetParams on an empty store returns the zero value -- so an absent block must mean "the binary's
	// own policy applies unchanged", exactly as it did before this existed.  The opposite sentinel
	// ("an empty list permits nothing") would stop every chain attesting the moment this shipped.
	EnclaveTrustPolicy EnclaveTrustPolicy `protobuf:"bytes,29,opt,name=enclave_trust_policy,json=enclaveTrustPolicy,proto3" json:"enclave_trust_policy"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_417091470738d6b1, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCreateWalletIncentive() types.Coin {
	if m != nil {
		return m.CreateWalletIncentive
	}
	return types.Coin{}
}

func (m *Params) GetCreateEphemeralWalletIncentive() types.Coin {
	if m != nil {
		return m.CreateEphemeralWalletIncentive
	}
	return types.Coin{}
}

func (m *Params) GetCreateWalletTransparentIncentive() types.Coin {
	if m != nil {
		return m.CreateWalletTransparentIncentive
	}
	return types.Coin{}
}

func (m *Params) GetCreateEphemeralWalletTransparentIncentive() types.Coin {
	if m != nil {
		return m.CreateEphemeralWalletTransparentIncentive
	}
	return types.Coin{}
}

func (m *Params) GetCreateCredentialFee() string {
	if m != nil {
		return m.CreateCredentialFee
	}
	return ""
}

func (m *Params) GetEkycSubmitNewAppRoyaltyPercentage() string {
	if m != nil {
		return m.EkycSubmitNewAppRoyaltyPercentage
	}
	return ""
}

func (m *Params) GetEkycSubmitReuseAppRoyaltyPercentage() string {
	if m != nil {
		return m.EkycSubmitReuseAppRoyaltyPercentage
	}
	return ""
}

func (m *Params) GetEkycSubmitReuseProviderRoyaltyPercentage() string {
	if m != nil {
		return m.EkycSubmitReuseProviderRoyaltyPercentage
	}
	return ""
}

func (m *Params) GetEkycIdentityOwnerRoyaltyPercentage() string {
	if m != nil {
		return m.EkycIdentityOwnerRoyaltyPercentage
	}
	return ""
}

func (m *Params) GetCreateBulkCredentialsFee() string {
	if m != nil {
		return m.CreateBulkCredentialsFee
	}
	return ""
}

func (m *Params) GetUpdateCredentialFee() string {
	if m != nil {
		return m.UpdateCredentialFee
	}
	return ""
}

func (m *Params) GetUpdateCredentialPolicyVersion() uint32 {
	if m != nil {
		return m.UpdateCredentialPolicyVersion
	}
	return 0
}

func (m *Params) GetUpdateCredentialMaxIdentityAliases() uint32 {
	if m != nil {
		return m.UpdateCredentialMaxIdentityAliases
	}
	return 0
}

func (m *Params) GetUpdateCredentialMaxLifeEvents() uint32 {
	if m != nil {
		return m.UpdateCredentialMaxLifeEvents
	}
	return 0
}

func (m *Params) GetUpdateNameMaxEditDistance() uint32 {
	if m != nil {
		return m.UpdateNameMaxEditDistance
	}
	return 0
}

func (m *Params) GetUpdateNameMaxEditDistancePercent() uint32 {
	if m != nil {
		return m.UpdateNameMaxEditDistancePercent
	}
	return 0
}

func (m *Params) GetUpdateBirthdateMaxYearDelta() uint32 {
	if m != nil {
		return m.UpdateBirthdateMaxYearDelta
	}
	return 0
}

func (m *Params) GetUpdateCredentialMinBlocksBetweenUpdates() int64 {
	if m != nil {
		return m.UpdateCredentialMinBlocksBetweenUpdates
	}
	return 0
}

func (m *Params) GetUpdateCredentialAllowLastNameLifeEvent() bool {
	if m != nil {
		return m.UpdateCredentialAllowLastNameLifeEvent
	}
	return false
}

func (m *Params) GetUpdateCredentialAllowGenderChange() bool {
	if m != nil {
		return m.UpdateCredentialAllowGenderChange
	}
	return false
}

func (m *Params) GetSuspiciousTransactionThreshold() string {
	if m != nil {
		return m.SuspiciousTransactionThreshold
	}
	return ""
}

func (m *Params) GetSuspiciousTransactionWindowSeconds() int64 {
	if m != nil {
		return m.SuspiciousTransactionWindowSeconds
	}
	return 0
}

func (m *Params) GetSuspiciousTransactionThresholdOverrides() []SuspiciousThresholdOverride {
	if m != nil {
		return m.SuspiciousTransactionThresholdOverrides
	}
	return nil
}

func (m *Params) GetAllowTransferWithoutEkyc() bool {
	if m != nil {
		return m.AllowTransferWithoutEkyc
	}
	return false
}

func (m *Params) GetBlockTransferWithoutOptInReason() bool {
	if m != nil {
		return m.BlockTransferWithoutOptInReason
	}
	return false
}

func (m *Params) GetUpdateCredentialMaxChangedIdentityFields() uint32 {
	if m != nil {
		return m.UpdateCredentialMaxChangedIdentityFields
	}
	return 0
}

func (m *Params) GetSignRecoverKeyGuardianAssertionMode() uint32 {
	if m != nil {
		return m.SignRecoverKeyGuardianAssertionMode
	}
	return 0
}

func (m *Params) GetReleaseAddressOnUnbond() bool {
	if m != nil {
		return m.ReleaseAddressOnUnbond
	}
	return false
}

func (m *Params) GetEnclaveTrustPolicy() EnclaveTrustPolicy {
	if m != nil {
		return m.EnclaveTrustPolicy
	}
	return EnclaveTrustPolicy{}
}

// One jurisdiction's reporting threshold, in that jurisdiction's own currency.
type SuspiciousThresholdOverride struct {
	// ISO 3166-1 alpha-2, matching the normalized Citizenship/Residency fields on a credential
	// (tx_create_credential.go normalizes both through gountries to Alpha2).
	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	// e.g. "500000php".  The keeper converts this to a common unit through the pricefeed before the
	// enclave sees it; the enclave has no pricefeed access of its own.
	Threshold string `protobuf:"bytes,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
}

func (m *SuspiciousThresholdOverride) Reset()         { *m = SuspiciousThresholdOverride{} }
func (m *SuspiciousThresholdOverride) String() string { return proto.CompactTextString(m) }
func (*SuspiciousThresholdOverride) ProtoMessage()    {}
func (*SuspiciousThresholdOverride) Descriptor() ([]byte, []int) {
	return fileDescriptor_417091470738d6b1, []int{1}
}
func (m *SuspiciousThresholdOverride) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SuspiciousThresholdOverride) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SuspiciousThresholdOverride.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SuspiciousThresholdOverride) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuspiciousThresholdOverride.Merge(m, src)
}
func (m *SuspiciousThresholdOverride) XXX_Size() int {
	return m.Size()
}
func (m *SuspiciousThresholdOverride) XXX_DiscardUnknown() {
	xxx_messageInfo_SuspiciousThresholdOverride.DiscardUnknown(m)
}

var xxx_messageInfo_SuspiciousThresholdOverride proto.InternalMessageInfo

func (m *SuspiciousThresholdOverride) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *SuspiciousThresholdOverride) GetThreshold() string {
	if m != nil {
		return m.Threshold
	}
	return ""
}

// What governance is allowed to say about which enclaves this chain trusts.
//
// GOVERNANCE MAY ONLY SUBTRACT.  The binary carries the most permissive set it will ever honour --
// that set is hashed into MRENCLAVE -- and this block can only remove from it:
//
//	effective = (compiled ∩ governance) ∪ {UpToDate}
//
// The asymmetry is the whole design, not a limitation.  Tightening is the move an operator actually
// needs (a host gets its microcode patched; a new advisory lands) and it should not cost a rebuild,
// a new enclave identity and a fleet upgrade.  Loosening beyond the build must keep costing exactly
// that, because a measurement is only worth something if it is an upper bound on what the node will
// accept -- otherwise two nodes with the same MRENCLAVE could trust different things.
//
// It is also what makes it safe to hand this to the ENCLAVE at all.  The enclave hears about the
// chain through the node process, which is unmeasured host code.  If the host could WIDEN the
// policy, its operator would say "accept anything", stand up a fake peer and be handed the
// sealed-table secret -- the enclave defeated through its own configuration channel.  Because the
// push can only narrow, a hostile host achieves nothing but making its own enclave refuse everyone.
//
// See x/qadena/common/tcbpolicy.go, which implements this and holds the compiled set.
type EnclaveTrustPolicy struct {
	// Canonical ego tcbstatus names: "UpToDate", "ConfigurationNeeded", "SWHardeningNeeded",
	// "ConfigurationAndSWHardeningNeeded", "OutOfDateConfigurationNeeded", "OutOfDate", "Revoked".
	//
	// EMPTY MEANS UNRESTRICTED -- the compiled set applies as-is.  A name not on the compiled list is
	// accepted by Validate but has no effect, because the intersection drops it; naming "OutOfDate"
	// here does NOT admit it.
	//
	// "UpToDate" is permitted whether or not it appears here.  A proposal cannot remove it, so no
	// vote -- mistaken or malicious -- can leave the fleet unable to attest at all, which is the one
	// failure this design could otherwise create and could then only recover from with a rebuild.
	PermittedTcbStatuses []string `protobuf:"bytes,1,rep,name=permitted_tcb_statuses,json=permittedTcbStatuses,proto3" json:"permitted_tcb_statuses,omitempty"`
}

func (m *EnclaveTrustPolicy) Reset()         { *m = EnclaveTrustPolicy{} }
func (m *EnclaveTrustPolicy) String() string { return proto.CompactTextString(m) }
func (*EnclaveTrustPolicy) ProtoMessage()    {}
func (*EnclaveTrustPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_417091470738d6b1, []int{2}
}
func (m *EnclaveTrustPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EnclaveTrustPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EnclaveTrustPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EnclaveTrustPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnclaveTrustPolicy.Merge(m, src)
}
func (m *EnclaveTrustPolicy) XXX_Size() int {
	return m.Size()
}
func (m *EnclaveTrustPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_EnclaveTrustPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_EnclaveTrustPolicy proto.InternalMessageInfo

func (m *EnclaveTrustPolicy) GetPermittedTcbStatuses() []string {
	if m != nil {
		return m.PermittedTcbStatuses
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "qadena.qadena.Params")
	proto.RegisterType((*SuspiciousThresholdOverride)(nil), "qadena.qadena.SuspiciousThresholdOverride")
	proto.RegisterType((*EnclaveTrustPolicy)(nil), "qadena.qadena.EnclaveTrustPolicy")
}

func init() { proto.RegisterFile("qadena/qadena/params.proto", fileDescriptor_417091470738d6b1) }

var fileDescriptor_417091470738d6b1 = []byte{
	// 1260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0x4f, 0x73, 0x13, 0x37,
	0x1b, 0xc0, 0xb3, 0x84, 0x17, 0x88, 0x78, 0x79, 0xdf, 0xb2, 0x24, 0xa0, 0x24, 0xe0, 0x38, 0xa6,
	0x80, 0x9b, 0x82, 0x5d, 0x02, 0x3d, 0x94, 0x69, 0x67, 0x1a, 0x43, 0xf8, 0x33, 0x25, 0x24, 0x6c,
	0x42, 0x19, 0xfa, 0x67, 0x34, 0xf2, 0xee, 0x13, 0x5b, 0x93, 0xb5, 0xb4, 0x48, 0x5a, 0x3b, 0xfb,
	0x15, 0x3a, 0xed, 0x4c, 0x4f, 0x3d, 0xf5, 0xd0, 0x8f, 0xd0, 0x6b, 0xbf, 0x01, 0x47, 0x8e, 0x3d,
	0x31, 0x1d, 0x38, 0xb4, 0xe7, 0x7e, 0x82, 0x8e, 0xa4, 0x75, 0x9c, 0xd8, 0xeb, 0xa4, 0x97, 0x78,
	0xb3, 0xcf, 0x4f, 0xbf, 0x7d, 0xf4, 0x3c, 0x2b, 0xad, 0xd0, 0xdc, 0x4b, 0x1a, 0x01, 0xa7, 0xf5,
	0xfc, 0x27, 0xa1, 0x92, 0x76, 0x54, 0x2d, 0x91, 0x42, 0x0b, 0xff, 0x8c, 0xbb, 0x59, 0x73, 0x3f,
	0x73, 0x67, 0x69, 0x87, 0x71, 0x51, 0xb7, 0x7f, 0x1d, 0x31, 0x37, 0xdd, 0x12, 0x2d, 0x61, 0x2f,
	0xeb, 0xe6, 0x2a, 0xbf, 0x5b, 0x0a, 0x85, 0xea, 0x08, 0x55, 0x6f, 0x52, 0x05, 0xf5, 0xee, 0xcd,
	0x26, 0x68, 0x7a, 0xb3, 0x1e, 0x0a, 0xc6, 0x5d, 0xbc, 0xf2, 0xfd, 0x0c, 0x3a, 0xb1, 0x61, 0x1f,
	0xe4, 0x67, 0xe8, 0x42, 0x28, 0x81, 0x6a, 0x20, 0x3d, 0x1a, 0xc7, 0xa0, 0x09, 0xe3, 0x21, 0x70,
	0xcd, 0xba, 0x80, 0xbd, 0xb2, 0x57, 0x3d, 0xbd, 0x3c, 0x5b, 0x73, 0xb2, 0x9a, 0x91, 0xd5, 0x72,
	0x59, 0xed, 0xae, 0x60, 0xbc, 0x71, 0xf5, 0xd5, 0x9b, 0x85, 0x89, 0xbf, 0xdf, 0x2c, 0x94, 0x32,
	0xda, 0x89, 0xef, 0x54, 0xc6, 0x78, 0x2a, 0xc1, 0x8c, 0x8b, 0x3c, 0xb7, 0x81, 0x47, 0xfd, 0xfb,
	0xfe, 0x4f, 0x1e, 0x5a, 0xcc, 0xc7, 0x40, 0xd2, 0x86, 0x0e, 0x48, 0x1a, 0x8f, 0x66, 0x71, 0xec,
	0xa8, 0x2c, 0x3e, 0xca, 0xb3, 0xa8, 0x1e, 0xc8, 0x62, 0xbc, 0xb1, 0x12, 0x94, 0x1c, 0xb3, 0xda,
	0x47, 0x86, 0x13, 0xfb, 0xd9, 0x43, 0x97, 0x0f, 0x4e, 0x46, 0x4b, 0xca, 0x55, 0x42, 0x25, 0xf0,
	0xfd, 0xa9, 0x4d, 0x1e, 0x95, 0xda, 0x72, 0x9e, 0xda, 0x52, 0x51, 0x81, 0x0a, 0x9d, 0x95, 0xa0,
	0xbc, 0xbf, 0x58, 0x5b, 0x03, 0x66, 0x90, 0xde, 0x6f, 0x1e, 0xba, 0x31, 0x6e, 0x96, 0xc5, 0x89,
	0x1e, 0x3f, 0x2a, 0xd1, 0x4f, 0xf3, 0x44, 0x6f, 0x1f, 0x5e, 0xc3, 0x31, 0x29, 0x7f, 0x50, 0x58,
	0xcf, 0xc2, 0xdc, 0x97, 0x51, 0xfe, 0x32, 0x90, 0x50, 0x42, 0x64, 0x6e, 0xd2, 0x98, 0x6c, 0x03,
	0xe0, 0xff, 0x94, 0xbd, 0xea, 0x54, 0x70, 0xce, 0x05, 0xef, 0xee, 0xc5, 0xee, 0x03, 0xf8, 0x4f,
	0xd1, 0x55, 0xd8, 0xc9, 0x42, 0xa2, 0xd2, 0x66, 0x87, 0x69, 0xc2, 0xa1, 0x47, 0x68, 0x92, 0x10,
	0x29, 0x32, 0x1a, 0xeb, 0x8c, 0x24, 0x20, 0x8d, 0x9d, 0xb6, 0x00, 0x9f, 0xb0, 0x92, 0x45, 0x43,
	0x6f, 0x5a, 0xf8, 0x09, 0xf4, 0x56, 0x92, 0x24, 0x70, 0xe4, 0xc6, 0x1e, 0xe8, 0x3f, 0x43, 0xd5,
	0xfd, 0x4a, 0x09, 0xa9, 0x82, 0x71, 0xd2, 0x93, 0x56, 0x7a, 0x79, 0x20, 0x0d, 0x0c, 0x5d, 0xa8,
	0x25, 0xe8, 0xc6, 0xa8, 0x36, 0x91, 0xa2, 0xcb, 0x22, 0x90, 0x45, 0xee, 0x53, 0xd6, 0x5d, 0x1d,
	0x72, 0x6f, 0xe4, 0x23, 0x46, 0x1f, 0x10, 0xe4, 0xa5, 0x60, 0xb6, 0x3c, 0x3a, 0x23, 0xa2, 0xc7,
	0x8b, 0xcd, 0x53, 0xd6, 0x5c, 0x31, 0xf4, 0xa3, 0x1c, 0x5e, 0x37, 0xec, 0xa8, 0xf3, 0x33, 0x34,
	0x9f, 0xb7, 0xa4, 0x99, 0xc6, 0x3b, 0xfb, 0xfa, 0xa2, 0x6c, 0x63, 0x90, 0x15, 0x61, 0x87, 0x34,
	0xd2, 0x78, 0x67, 0xd0, 0x1c, 0x65, 0xba, 0xb3, 0x8c, 0x66, 0xd2, 0x24, 0x2a, 0xe8, 0xe8, 0x69,
	0xd7, 0x51, 0x17, 0x3c, 0xd8, 0xd1, 0x07, 0xa8, 0x3c, 0x3a, 0x26, 0x11, 0x31, 0x0b, 0x33, 0xd2,
	0x05, 0xa9, 0x98, 0xe0, 0xf8, 0xbf, 0x65, 0xaf, 0x7a, 0x26, 0xb8, 0x34, 0x3c, 0x7c, 0xc3, 0x52,
	0x5f, 0x3a, 0xc8, 0xd4, 0x63, 0x54, 0xd4, 0xa1, 0xbb, 0x83, 0x02, 0xd1, 0x98, 0x51, 0x05, 0x0a,
	0x9f, 0xb1, 0xba, 0xca, 0xb0, 0x6e, 0x8d, 0xee, 0xf6, 0xcb, 0xb3, 0xe2, 0x48, 0xff, 0x21, 0x5a,
	0x2c, 0x76, 0xc6, 0x6c, 0x1b, 0x08, 0x74, 0x81, 0x6b, 0x85, 0xff, 0x57, 0x9c, 0xdd, 0x1a, 0xdd,
	0x7d, 0xcc, 0xb6, 0x61, 0xd5, 0x42, 0xfe, 0xe7, 0x28, 0x07, 0x08, 0xa7, 0x1d, 0xb0, 0x0e, 0x88,
	0x98, 0x26, 0x11, 0x53, 0x9a, 0xf2, 0x10, 0xf0, 0xff, 0xad, 0x65, 0xd6, 0x41, 0x4f, 0x68, 0x07,
	0xd6, 0xe8, 0xee, 0x6a, 0xc4, 0xf4, 0xbd, 0x1c, 0xf0, 0xd7, 0xd1, 0x95, 0x43, 0x0d, 0xfd, 0x8e,
	0xe3, 0xf7, 0xac, 0xa9, 0x3c, 0xd6, 0x94, 0xf7, 0xdb, 0xbf, 0x87, 0x16, 0x72, 0x61, 0x93, 0x49,
	0xdd, 0xb6, 0x57, 0xc6, 0x9a, 0x01, 0x95, 0x24, 0x82, 0x58, 0x53, 0x7c, 0xd6, 0xaa, 0xe6, 0x1d,
	0xd6, 0xe8, 0x53, 0x6b, 0x74, 0xf7, 0x05, 0x50, 0x79, 0xcf, 0x20, 0xfe, 0xb7, 0xe8, 0x7a, 0x41,
	0x89, 0x18, 0x27, 0xcd, 0x58, 0x84, 0x3b, 0x8a, 0x34, 0x41, 0xf7, 0x00, 0x38, 0x71, 0x90, 0xc2,
	0x7e, 0xd9, 0xab, 0x4e, 0x06, 0xd7, 0x46, 0xaa, 0xc5, 0x78, 0xc3, 0x0e, 0x68, 0x38, 0xfe, 0x99,
	0xc3, 0xfd, 0x6f, 0x8a, 0xf4, 0x34, 0x8e, 0x45, 0x8f, 0xc4, 0x54, 0x69, 0x57, 0x8b, 0x41, 0x37,
	0xf0, 0xb9, 0xb2, 0x57, 0x3d, 0x15, 0x5c, 0x1d, 0xd6, 0xaf, 0x98, 0x11, 0x8f, 0xa9, 0xd2, 0xa6,
	0x1e, 0x7b, 0x6d, 0xf1, 0x37, 0xf6, 0x6a, 0x3a, 0x62, 0x6f, 0x01, 0x37, 0x0b, 0x35, 0x6c, 0x53,
	0xde, 0x02, 0x3c, 0x6d, 0xb5, 0x8b, 0x85, 0xda, 0x07, 0x96, 0xbc, 0x6b, 0x41, 0xff, 0x21, 0x2a,
	0xab, 0x54, 0x25, 0x2c, 0x64, 0x22, 0x55, 0x6e, 0x93, 0xa4, 0xa1, 0x66, 0x82, 0x13, 0xdd, 0x96,
	0xa0, 0xda, 0x22, 0x8e, 0xf0, 0x8c, 0x5d, 0x0d, 0xa5, 0x01, 0xb7, 0x35, 0xc0, 0xb6, 0xfa, 0x94,
	0xff, 0x14, 0x5d, 0x19, 0x63, 0xea, 0x31, 0x1e, 0x89, 0x1e, 0x51, 0x10, 0x0a, 0x1e, 0x29, 0x7c,
	0xde, 0x56, 0xb4, 0x52, 0xa8, 0x7b, 0x6e, 0xd1, 0x4d, 0x47, 0xfa, 0x3f, 0x78, 0x68, 0xe9, 0xa8,
	0xec, 0x88, 0xe8, 0x82, 0x94, 0x2c, 0x02, 0x85, 0x2f, 0x94, 0x27, 0xab, 0xa7, 0x97, 0x97, 0x6a,
	0x07, 0x4e, 0x1e, 0xb5, 0xcd, 0xc1, 0x73, 0xfa, 0x63, 0xd6, 0xf3, 0x21, 0x8d, 0xe3, 0xe6, 0xdb,
	0x11, 0x5c, 0x3b, 0x7c, 0x66, 0x7d, 0x5a, 0x99, 0xed, 0xc6, 0x15, 0xdb, 0x66, 0xb2, 0x0d, 0x92,
	0xf4, 0x98, 0x6e, 0x8b, 0x54, 0x13, 0xb3, 0x57, 0x61, 0x6c, 0x8b, 0x8e, 0x2d, 0xb2, 0x95, 0x13,
	0xcf, 0x1d, 0xb0, 0xba, 0x93, 0x85, 0xfe, 0x1a, 0x7a, 0xdf, 0xbe, 0x64, 0xa3, 0xc3, 0x45, 0x62,
	0x3e, 0x4a, 0x44, 0x02, 0x55, 0x82, 0xe3, 0x39, 0xeb, 0x59, 0xb0, 0xec, 0x90, 0x67, 0x3d, 0xd1,
	0x8f, 0x78, 0x60, 0x31, 0xb3, 0x63, 0x17, 0x2f, 0x76, 0xf7, 0x0e, 0x44, 0x83, 0x8d, 0x64, 0x9b,
	0x41, 0x1c, 0x29, 0x3c, 0x6b, 0x57, 0x47, 0xb5, 0x60, 0xe1, 0xbb, 0x97, 0x21, 0xea, 0x6f, 0x27,
	0xf7, 0x2d, 0x6f, 0xbe, 0x34, 0x8a, 0xb5, 0x4c, 0x5a, 0xa1, 0x29, 0x32, 0xd9, 0x81, 0x8c, 0xb4,
	0x52, 0x2a, 0x23, 0x46, 0x39, 0xa1, 0x4a, 0x81, 0xb4, 0xad, 0xe8, 0x88, 0x08, 0xf0, 0xbc, 0x75,
	0x5f, 0x36, 0x7c, 0xe0, 0xf0, 0x2f, 0x20, 0x7b, 0x90, 0xc3, 0x2b, 0x7d, 0x76, 0x4d, 0x44, 0xe0,
	0x7f, 0x82, 0x66, 0x25, 0xc4, 0x40, 0xcd, 0x67, 0x2b, 0x8a, 0x24, 0x28, 0x45, 0x04, 0x27, 0x29,
	0x6f, 0x0a, 0x1e, 0xe1, 0x8b, 0x76, 0xee, 0xe7, 0x73, 0x60, 0xc5, 0xc5, 0xd7, 0xf9, 0x33, 0x1b,
	0xf5, 0x5f, 0xa0, 0x69, 0xe0, 0x61, 0x4c, 0xbb, 0x40, 0xb4, 0x4c, 0x95, 0xce, 0x37, 0x5e, 0x7c,
	0xc9, 0x1e, 0x12, 0x16, 0x87, 0x3a, 0xbf, 0xea, 0xd0, 0x2d, 0x43, 0xba, 0xbd, 0x37, 0x6f, 0xb8,
	0x0f, 0x23, 0x91, 0x3b, 0x1f, 0xff, 0xf5, 0xcb, 0x82, 0xf7, 0xdd, 0x9f, 0xbf, 0x2e, 0x5d, 0x6f,
	0x31, 0xdd, 0x4e, 0x9b, 0xb5, 0x50, 0x74, 0xea, 0xe1, 0xad, 0x97, 0x1a, 0xc2, 0x76, 0x7e, 0xc0,
	0x25, 0xdd, 0x5b, 0xf5, 0xdd, 0xfe, 0x61, 0xd7, 0x9d, 0x41, 0x2b, 0x5f, 0xa3, 0xf9, 0x43, 0x5e,
	0x30, 0x1f, 0xa3, 0x93, 0xa1, 0x48, 0xb9, 0x96, 0x99, 0x3d, 0x92, 0x4e, 0x05, 0xfd, 0x7f, 0xfd,
	0x8b, 0x68, 0x6a, 0xb0, 0xc2, 0x8e, 0xd9, 0xd8, 0xe0, 0xc6, 0x9d, 0xe3, 0x26, 0x9b, 0xca, 0x06,
	0xf2, 0x47, 0xe7, 0xe0, 0xdf, 0x46, 0xe7, 0x13, 0x90, 0x1d, 0xa6, 0x35, 0x44, 0x44, 0x87, 0x4d,
	0xa2, 0x34, 0xd5, 0xa9, 0xf9, 0x50, 0x78, 0xe5, 0xc9, 0xea, 0x54, 0x30, 0xbd, 0x17, 0xdd, 0x0a,
	0x9b, 0x9b, 0x79, 0xcc, 0x19, 0x1b, 0xab, 0xaf, 0xde, 0x96, 0xbc, 0xd7, 0x6f, 0x4b, 0xde, 0x1f,
	0x6f, 0x4b, 0xde, 0x8f, 0xef, 0x4a, 0x13, 0xaf, 0xdf, 0x95, 0x26, 0x7e, 0x7f, 0x57, 0x9a, 0xf8,
	0xea, 0xc3, 0x7f, 0x37, 0x6d, 0x9d, 0x25, 0xa0, 0x9a, 0x27, 0xec, 0x59, 0xfc, 0xd6, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x91, 0x31, 0xff, 0xfb, 0x01, 0x0c, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CreateWalletIncentive.Equal(&that1.CreateWalletIncentive) {
		return false
	}
	if !this.CreateEphemeralWalletIncentive.Equal(&that1.CreateEphemeralWalletIncentive) {
		return false
	}
	if !this.CreateWalletTransparentIncentive.Equal(&that1.CreateWalletTransparentIncentive) {
		return false
	}
	if !this.CreateEphemeralWalletTransparentIncentive.Equal(&that1.CreateEphemeralWalletTransparentIncentive) {
		return false
	}
	if this.CreateCredentialFee != that1.CreateCredentialFee {
		return false
	}
	if this.EkycSubmitNewAppRoyaltyPercentage != that1.EkycSubmitNewAppRoyaltyPercentage {
		return false
	}
	if this.EkycSubmitReuseAppRoyaltyPercentage != that1.EkycSubmitReuseAppRoyaltyPercentage {
		return false
	}
	if this.EkycSubmitReuseProviderRoyaltyPercentage != that1.EkycSubmitReuseProviderRoyaltyPercentage {
		return false
	}
	if this.EkycIdentityOwnerRoyaltyPercentage != that1.EkycIdentityOwnerRoyaltyPercentage {
		return false
	}
	if this.CreateBulkCredentialsFee != that1.CreateBulkCredentialsFee {
		return false
	}
	if this.UpdateCredentialFee != that1.UpdateCredentialFee {
		return false
	}
	if this.UpdateCredentialPolicyVersion != that1.UpdateCredentialPolicyVersion {
		return false
	}
	if this.UpdateCredentialMaxIdentityAliases != that1.UpdateCredentialMaxIdentityAliases {
		return false
	}
	if this.UpdateCredentialMaxLifeEvents != that1.UpdateCredentialMaxLifeEvents {
		return false
	}
	if this.UpdateNameMaxEditDistance != that1.UpdateNameMaxEditDistance {
		return false
	}
	if this.UpdateNameMaxEditDistancePercent != that1.UpdateNameMaxEditDistancePercent {
		return false
	}
	if this.UpdateBirthdateMaxYearDelta != that1.UpdateBirthdateMaxYearDelta {
		return false
	}
	if this.UpdateCredentialMinBlocksBetweenUpdates != that1.UpdateCredentialMinBlocksBetweenUpdates {
		return false
	}
	if this.UpdateCredentialAllowLastNameLifeEvent != that1.UpdateCredentialAllowLastNameLifeEvent {
		return false
	}
	if this.UpdateCredentialAllowGenderChange != that1.UpdateCredentialAllowGenderChange {
		return false
	}
	if this.SuspiciousTransactionThreshold != that1.SuspiciousTransactionThreshold {
		return false
	}
	if this.SuspiciousTransactionWindowSeconds != that1.SuspiciousTransactionWindowSeconds {
		return false
	}
	if len(this.SuspiciousTransactionThresholdOverrides) != len(that1.SuspiciousTransactionThresholdOverrides) {
		return false
	}
	for i := range this.SuspiciousTransactionThresholdOverrides {
		if !this.SuspiciousTransactionThresholdOverrides[i].Equal(&that1.SuspiciousTransactionThresholdOverrides[i]) {
			return false
		}
	}
	if this.AllowTransferWithoutEkyc != that1.AllowTransferWithoutEkyc {
		return false
	}
	if this.BlockTransferWithoutOptInReason != that1.BlockTransferWithoutOptInReason {
		return false
	}
	if this.UpdateCredentialMaxChangedIdentityFields != that1.UpdateCredentialMaxChangedIdentityFields {
		return false
	}
	if this.SignRecoverKeyGuardianAssertionMode != that1.SignRecoverKeyGuardianAssertionMode {
		return false
	}
	if this.ReleaseAddressOnUnbond != that1.ReleaseAddressOnUnbond {
		return false
	}
	if !this.EnclaveTrustPolicy.Equal(&that1.EnclaveTrustPolicy) {
		return false
	}
	return true
}
func (this *SuspiciousThresholdOverride) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SuspiciousThresholdOverride)
	if !ok {
		that2, ok := that.(SuspiciousThresholdOverride)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Country != that1.Country {
		return false
	}
	if this.Threshold != that1.Threshold {
		return false
	}
	return true
}
func (this *EnclaveTrustPolicy) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EnclaveTrustPolicy)
	if !ok {
		that2, ok := that.(EnclaveTrustPolicy)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.PermittedTcbStatuses) != len(that1.PermittedTcbStatuses) {
		return false
	}
	for i := range this.PermittedTcbStatuses {
		if this.PermittedTcbStatuses[i] != that1.PermittedTcbStatuses[i] {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.EnclaveTrustPolicy.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xea
	if m.ReleaseAddressOnUnbond {
		i--
		if m.ReleaseAddressOnUnbond {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe0
	}
	if m.SignRecoverKeyGuardianAssertionMode != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SignRecoverKeyGuardianAssertionMode))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd8
	}
	if m.BlockTransferWithoutOptInReason {
		i--
		if m.BlockTransferWithoutOptInReason {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd0
	}
	if m.UpdateCredentialMaxChangedIdentityFields != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpdateCredentialMaxChangedIdentityFields))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc8
	}
	if m.AllowTransferWithoutEkyc {
		i--
		if m.AllowTransferWithoutEkyc {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	if len(m.SuspiciousTransactionThresholdOverrides) > 0 {
		for iNdEx := len(m.SuspiciousTransactionThresholdOverrides) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SuspiciousTransactionThresholdOverrides[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xba
		}
	}
	if m.SuspiciousTransactionWindowSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SuspiciousTransactionWindowSeconds))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if len(m.SuspiciousTransactionThreshold) > 0 {
		i -= len(m.SuspiciousTransactionThreshold)
		copy(dAtA[i:], m.SuspiciousTransactionThreshold)
		i = encodeVarintParams(dAtA, i, uint64(len(m.SuspiciousTransactionThreshold)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if m.UpdateCredentialAllowGenderChange {
		i--
		if m.UpdateCredentialAllowGenderChange {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.UpdateCredentialAllowLastNameLifeEvent {
		i--
		if m.UpdateCredentialAllowLastNameLifeEvent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.UpdateCredentialMinBlocksBetweenUpdates != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpdateCredentialMinBlocksBetweenUpdates))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.UpdateBirthdateMaxYearDelta != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpdateBirthdateMaxYearDelta))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.UpdateNameMaxEditDistancePercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpdateNameMaxEditDistancePercent))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.UpdateNameMaxEditDistance != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpdateNameMaxEditDistance))
		i--
		dAtA[i] = 0x78
	}
	if m.UpdateCredentialMaxLifeEvents != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpdateCredentialMaxLifeEvents))
		i--
		dAtA[i] = 0x70
	}
	if m.UpdateCredentialMaxIdentityAliases != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpdateCredentialMaxIdentityAliases))
		i--
		dAtA[i] = 0x68
	}
	if m.UpdateCredentialPolicyVersion != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpdateCredentialPolicyVersion))
		i--
		dAtA[i] = 0x60
	}
	if len(m.UpdateCredentialFee) > 0 {
		i -= len(m.UpdateCredentialFee)
		copy(dAtA[i:], m.UpdateCredentialFee)
		i = encodeVarintParams(dAtA, i, uint64(len(m.UpdateCredentialFee)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.CreateBulkCredentialsFee) > 0 {
		i -= len(m.CreateBulkCredentialsFee)
		copy(dAtA[i:], m.CreateBulkCredentialsFee)
		i = encodeVarintParams(dAtA, i, uint64(len(m.CreateBulkCredentialsFee)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.EkycIdentityOwnerRoyaltyPercentage) > 0 {
		i -= len(m.EkycIdentityOwnerRoyaltyPercentage)
		copy(dAtA[i:], m.EkycIdentityOwnerRoyaltyPercentage)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EkycIdentityOwnerRoyaltyPercentage)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.EkycSubmitReuseProviderRoyaltyPercentage) > 0 {
		i -= len(m.EkycSubmitReuseProviderRoyaltyPercentage)
		copy(dAtA[i:], m.EkycSubmitReuseProviderRoyaltyPercentage)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EkycSubmitReuseProviderRoyaltyPercentage)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.EkycSubmitReuseAppRoyaltyPercentage) > 0 {
		i -= len(m.EkycSubmitReuseAppRoyaltyPercentage)
		copy(dAtA[i:], m.EkycSubmitReuseAppRoyaltyPercentage)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EkycSubmitReuseAppRoyaltyPercentage)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.EkycSubmitNewAppRoyaltyPercentage) > 0 {
		i -= len(m.EkycSubmitNewAppRoyaltyPercentage)
		copy(dAtA[i:], m.EkycSubmitNewAppRoyaltyPercentage)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EkycSubmitNewAppRoyaltyPercentage)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CreateCredentialFee) > 0 {
		i -= len(m.CreateCredentialFee)
		copy(dAtA[i:], m.CreateCredentialFee)
		i = encodeVarintParams(dAtA, i, uint64(len(m.CreateCredentialFee)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.CreateEphemeralWalletTransparentIncentive.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.CreateWalletTransparentIncentive.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.CreateEphemeralWalletIncentive.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CreateWalletIncentive.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *SuspiciousThresholdOverride) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SuspiciousThresholdOverride) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SuspiciousThresholdOverride) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Threshold) > 0 {
		i -= len(m.Threshold)
		copy(dAtA[i:], m.Threshold)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Threshold)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Country) > 0 {
		i -= len(m.Country)
		copy(dAtA[i:], m.Country)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Country)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EnclaveTrustPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnclaveTrustPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EnclaveTrustPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PermittedTcbStatuses) > 0 {
		for iNdEx := len(m.PermittedTcbStatuses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PermittedTcbStatuses[iNdEx])
			copy(dAtA[i:], m.PermittedTcbStatuses[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.PermittedTcbStatuses[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CreateWalletIncentive.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.CreateEphemeralWalletIncentive.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.CreateWalletTransparentIncentive.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.CreateEphemeralWalletTransparentIncentive.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.CreateCredentialFee)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.EkycSubmitNewAppRoyaltyPercentage)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.EkycSubmitReuseAppRoyaltyPercentage)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.EkycSubmitReuseProviderRoyaltyPercentage)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.EkycIdentityOwnerRoyaltyPercentage)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.CreateBulkCredentialsFee)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.UpdateCredentialFee)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.UpdateCredentialPolicyVersion != 0 {
		n += 1 + sovParams(uint64(m.UpdateCredentialPolicyVersion))
	}
	if m.UpdateCredentialMaxIdentityAliases != 0 {
		n += 1 + sovParams(uint64(m.UpdateCredentialMaxIdentityAliases))
	}
	if m.UpdateCredentialMaxLifeEvents != 0 {
		n += 1 + sovParams(uint64(m.UpdateCredentialMaxLifeEvents))
	}
	if m.UpdateNameMaxEditDistance != 0 {
		n += 1 + sovParams(uint64(m.UpdateNameMaxEditDistance))
	}
	if m.UpdateNameMaxEditDistancePercent != 0 {
		n += 2 + sovParams(uint64(m.UpdateNameMaxEditDistancePercent))
	}
	if m.UpdateBirthdateMaxYearDelta != 0 {
		n += 2 + sovParams(uint64(m.UpdateBirthdateMaxYearDelta))
	}
	if m.UpdateCredentialMinBlocksBetweenUpdates != 0 {
		n += 2 + sovParams(uint64(m.UpdateCredentialMinBlocksBetweenUpdates))
	}
	if m.UpdateCredentialAllowLastNameLifeEvent {
		n += 3
	}
	if m.UpdateCredentialAllowGenderChange {
		n += 3
	}
	l = len(m.SuspiciousTransactionThreshold)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	if m.SuspiciousTransactionWindowSeconds != 0 {
		n += 2 + sovParams(uint64(m.SuspiciousTransactionWindowSeconds))
	}
	if len(m.SuspiciousTransactionThresholdOverrides) > 0 {
		for _, e := range m.SuspiciousTransactionThresholdOverrides {
			l = e.Size()
			n += 2 + l + sovParams(uint64(l))
		}
	}
	if m.AllowTransferWithoutEkyc {
		n += 3
	}
	if m.UpdateCredentialMaxChangedIdentityFields != 0 {
		n += 2 + sovParams(uint64(m.UpdateCredentialMaxChangedIdentityFields))
	}
	if m.BlockTransferWithoutOptInReason {
		n += 3
	}
	if m.SignRecoverKeyGuardianAssertionMode != 0 {
		n += 2 + sovParams(uint64(m.SignRecoverKeyGuardianAssertionMode))
	}
	if m.ReleaseAddressOnUnbond {
		n += 3
	}
	l = m.EnclaveTrustPolicy.Size()
	n += 2 + l + sovParams(uint64(l))
	return n
}

func (m *SuspiciousThresholdOverride) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Country)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Threshold)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *EnclaveTrustPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PermittedTcbStatuses) > 0 {
		for _, s := range m.PermittedTcbStatuses {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateWalletIncentive", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreateWalletIncentive.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateEphemeralWalletIncentive", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreateEphemeralWalletIncentive.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateWalletTransparentIncentive", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreateWalletTransparentIncentive.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateEphemeralWalletTransparentIncentive", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreateEphemeralWalletTransparentIncentive.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateCredentialFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreateCredentialFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EkycSubmitNewAppRoyaltyPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EkycSubmitNewAppRoyaltyPercentage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EkycSubmitReuseAppRoyaltyPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EkycSubmitReuseAppRoyaltyPercentage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EkycSubmitReuseProviderRoyaltyPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EkycSubmitReuseProviderRoyaltyPercentage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EkycIdentityOwnerRoyaltyPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EkycIdentityOwnerRoyaltyPercentage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateBulkCredentialsFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreateBulkCredentialsFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdateCredentialFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialPolicyVersion", wireType)
			}
			m.UpdateCredentialPolicyVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateCredentialPolicyVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialMaxIdentityAliases", wireType)
			}
			m.UpdateCredentialMaxIdentityAliases = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateCredentialMaxIdentityAliases |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialMaxLifeEvents", wireType)
			}
			m.UpdateCredentialMaxLifeEvents = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateCredentialMaxLifeEvents |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateNameMaxEditDistance", wireType)
			}
			m.UpdateNameMaxEditDistance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateNameMaxEditDistance |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateNameMaxEditDistancePercent", wireType)
			}
			m.UpdateNameMaxEditDistancePercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateNameMaxEditDistancePercent |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateBirthdateMaxYearDelta", wireType)
			}
			m.UpdateBirthdateMaxYearDelta = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateBirthdateMaxYearDelta |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialMinBlocksBetweenUpdates", wireType)
			}
			m.UpdateCredentialMinBlocksBetweenUpdates = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateCredentialMinBlocksBetweenUpdates |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialAllowLastNameLifeEvent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UpdateCredentialAllowLastNameLifeEvent = bool(v != 0)
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialAllowGenderChange", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UpdateCredentialAllowGenderChange = bool(v != 0)
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuspiciousTransactionThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SuspiciousTransactionThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuspiciousTransactionWindowSeconds", wireType)
			}
			m.SuspiciousTransactionWindowSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SuspiciousTransactionWindowSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuspiciousTransactionThresholdOverrides", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SuspiciousTransactionThresholdOverrides = append(m.SuspiciousTransactionThresholdOverrides, SuspiciousThresholdOverride{})
			if err := m.SuspiciousTransactionThresholdOverrides[len(m.SuspiciousTransactionThresholdOverrides)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowTransferWithoutEkyc", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowTransferWithoutEkyc = bool(v != 0)
		case 25:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateCredentialMaxChangedIdentityFields", wireType)
			}
			m.UpdateCredentialMaxChangedIdentityFields = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateCredentialMaxChangedIdentityFields |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTransferWithoutOptInReason", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BlockTransferWithoutOptInReason = bool(v != 0)
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignRecoverKeyGuardianAssertionMode", wireType)
			}
			m.SignRecoverKeyGuardianAssertionMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignRecoverKeyGuardianAssertionMode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 28:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseAddressOnUnbond", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReleaseAddressOnUnbond = bool(v != 0)
		case 29:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnclaveTrustPolicy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EnclaveTrustPolicy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SuspiciousThresholdOverride) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SuspiciousThresholdOverride: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SuspiciousThresholdOverride: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Country", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Country = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Threshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnclaveTrustPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnclaveTrustPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnclaveTrustPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PermittedTcbStatuses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PermittedTcbStatuses = append(m.PermittedTcbStatuses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
