package main

// The secrets store: a separate, UNVERSIONED goleveldb for state that must never roll back.
//
// The enclave's main store is a rootmulti/IAVL tree so it can be rolled back to a chain height
// (see enclave_height.go).  But rootmulti.RollbackToVersion iterates EVERY mounted IAVL store --
// there is no way to exempt a prefix or a second store key from a rollback.  Some enclave state
// must survive one anyway:
//
//   SS interval shares and the privK cache   generated by GenerateSecretShare, which is
//                                            NONDETERMINISTIC and runs in a goroutine outside
//                                            block execution.  Rolling past a generation would
//                                            forget a private key whose public half is already
//                                            broadcast on chain -- every VShare encrypted to it
//                                            becomes permanently undecryptable, silently.
//   SS interval owners / pubK cache          the non-secret halves of the same records; they
//                                            must stay consistent with the shares.
//   the unvalidated-identity work queue      written by the same out-of-band goroutines.
//
// Key material is CUMULATIVE: a rolled-back chain merely leaves some keys unreferenced, which is
// harmless -- and if the chain rolls forward through that height again, the keys must still
// exist.  So the rule is: rollback never touches this DB, by construction, because it is not
// part of the tree that rollback operates on.
//
// Moving these writes out of the transaction cache also fixes a real race: the keygen goroutine
// used to write through s.CacheCtx, so a concurrent TransactionComplete{Success:false} re-derived
// the cache and silently destroyed a freshly generated private key.  Writes here are immediate
// and guarded by their own mutex; they are deliberately NOT transactional with the block, which
// is exactly the semantics secret material wants (persisting a share for a transaction that later
// failed costs an unreferenced share; losing a share for one that succeeded costs the key).
//
// Sealing is unchanged from the main store: deterministic MustSealStable for keys that must
// remain lookupable, nondeterministic MustSeal for values (see the accessors in enclave.go).

import (
	"sync"

	storetypes "cosmossdk.io/store/types"

	c "github.com/c3qtech/qadena_v3/x/qadena/common"
	"github.com/c3qtech/qadena_v3/x/qadena/types"
)

// secretsMutex guards multi-op sequences on the secrets DB (goleveldb's single ops are already
// atomic).  A dedicated mutex rather than s.mutex so there is no lock-ordering relationship with
// the params getters.  Only the leaf helpers below take it -- compound accessors must NOT, or
// they would self-deadlock.
var secretsMutex sync.RWMutex

// secretsStore presents the same Get/Set/Delete surface as the prefix stores the accessors used
// before, so retargeting a table is a one-line change in each accessor.
type secretsStore struct {
	s   *qadenaServer
	pfx []byte
}

func (s *qadenaServer) secrets(pfx string) secretsStore {
	return secretsStore{s: s, pfx: types.KeyPrefix(pfx)}
}

func (st secretsStore) raw(key []byte) []byte {
	k := make([]byte, 0, len(st.pfx)+len(key))
	k = append(k, st.pfx...)
	k = append(k, key...)
	return k
}

func (st secretsStore) Get(key []byte) []byte {
	secretsMutex.RLock()
	defer secretsMutex.RUnlock()
	b, err := st.s.SecretsDB.Get(st.raw(key))
	if err != nil {
		panic("qadena enclave: secrets read failed: " + err.Error())
	}
	return b
}

func (st secretsStore) Set(key, value []byte) {
	secretsMutex.Lock()
	defer secretsMutex.Unlock()
	// SetSync: a secret that only reached the OS buffer is a secret a power cut deletes
	if err := st.s.SecretsDB.SetSync(st.raw(key), value); err != nil {
		panic("qadena enclave: secrets write failed: " + err.Error())
	}
}

func (st secretsStore) Delete(key []byte) {
	secretsMutex.Lock()
	defer secretsMutex.Unlock()
	if err := st.s.SecretsDB.DeleteSync(st.raw(key)); err != nil {
		panic("qadena enclave: secrets delete failed: " + err.Error())
	}
}

// Keys returns a snapshot of every (prefix-stripped) key in the table.  A snapshot rather than a
// live iterator so callers can Get/Set per key afterwards without holding the mutex across their
// own reads -- Go's RWMutex is not reentrant and an RLock taken inside an RLock can deadlock
// behind a queued writer.
func (st secretsStore) Keys() [][]byte {
	secretsMutex.RLock()
	defer secretsMutex.RUnlock()
	it, err := st.s.SecretsDB.Iterator(st.pfx, storetypes.PrefixEndBytes(st.pfx))
	if err != nil {
		panic("qadena enclave: secrets iterate failed: " + err.Error())
	}
	defer it.Close()
	var keys [][]byte
	for ; it.Valid(); it.Next() {
		k := make([]byte, len(it.Key())-len(st.pfx))
		copy(k, it.Key()[len(st.pfx):])
		keys = append(keys, k)
	}
	return keys
}

// exportSecretsTable is exportTable (enclave.go) for a table living in the secrets DB:
// plaintext keys, plaintext EnclaveStoreString values.
func (s *qadenaServer) exportSecretsTable(pfx string) (tableMap map[string]string) {
	tableMap = make(map[string]string)
	store := s.secrets(pfx)
	for _, key := range store.Keys() {
		fixedKey := string(key[:len(key)-1])
		c.LoggerDebug(logger, "fixedKey "+fixedKey)
		var val types.EnclaveStoreString
		s.Cdc.MustUnmarshal(store.Get(key), &val)
		tableMap[fixedKey] = val.GetS()
	}
	return
}

// exportSealedSecretsTable is exportSealedTable (enclave.go) for a table living in the secrets
// DB: sealed keys, sealed EnclaveStoreString values.
func (s *qadenaServer) exportSealedSecretsTable(pfx string) (tableMap map[string]string) {
	tableMap = make(map[string]string)
	store := s.secrets(pfx)
	for _, key := range store.Keys() {
		plainKey := s.MustUnsealStable(key)
		fixedKey := string(plainKey[:len(plainKey)-1])
		c.LoggerDebug(logger, "fixedKey "+fixedKey)
		var val types.EnclaveStoreString
		s.Cdc.MustUnmarshal(s.MustUnseal(store.Get(key)), &val)
		tableMap[fixedKey] = val.GetS()
	}
	return
}
